site_name: polynom
site_url: https://berlinade.gitlab.io/polynom
site_dir: public

theme:
  name: material
  features:
    - search.suggest
    - search.highlight
    - content.tabs.link
    -
plugins:
  - search

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - polynom:
    - base: pages/polynom/_base.md
    - Chebyshev: pages/polynom/chebyshev.md
    - Gegenbauer: pages/polynom/gegenbauer.md
    - Lagrange: pages/polynom/lagrange.md
    - Legendre: pages/polynom/legendre.md
    - Monomial: pages/polynom/monomial.md
    - Newton: pages/polynom/newton.md
    - shared: pages/polynom/shared.md
