[project]
name = "exfill"
version = "0.0.14"
authors = [ 
    { name = "Jay Law", email = "mr-jay-law@protonmail.com" }
]
readme = "README.md"
description = "A small app to grab job postings from online job boards"
requires-python = ">=3.8"
dependencies = [
    "pandas",
    "beautifulsoup4",
    "selenium"
]

[project.urls]
homepage = "https://github.com/jay-law/job-scraper"
repository = "https://github.com/jay-law/job-scraper"
documentation = "https://github.com/jay-law/job-scraper"

[project.scripts]
cli-script = "exfill.extractor:main"

[build-system]
requires = [
    "setuptools>=45", 
    "setuptools_scm[toml]>=6.2"
]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "src"}
packages = [
 "exfill", 
 "exfill.parsers",
 "exfill.scrapers"]
