name: Lint

permissions:
   contents: write

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run black check
        uses: psf/black@stable
        with:
          options: "--check --diff"

      - name: Run black format
        if: failure()
        uses: psf/black@stable
        with:
          options: ""

      - name: Commit black format
        if: failure()
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Apply black to code"

