
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-12T22:54:58+1000",
 "dirty": false,
 "error": null,
 "full-revisionid": "189e6ecfd990beb4c3d78ec520f0a89723d2b8cf",
 "version": "0.15.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
