[build-system]
requires = ["poetry-core>=1.0.0", ]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "nylondetector"
version = "0.1.7"
description = ""
authors = ["Kwangsik Lee <lks21c@gmail.com>", ]

[tool.poetry.dependencies]
python = "^3.8"
#numpy = "^1.21.4"
#pandas = "^1.4.2"
tqdm = "^4.64.0"
#selenium = "^4.1.3"
aiohttp = "^3.8.1"
nest-asyncio = "^1.5.5"
#konlpy = "^0.6.0"
#matplotlib = "^3.5.1"
ujson = "^5.2.0"
requests = "^2.27.1"
fire = "^0.4.0"
beautifulsoup4 = "^4.11.1"
#python-dateutil = "^2.8.2"
#tweepy = "^4.8.0"
pytest-cov = "^3.0.0"
baram = "^0.1.6"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"

