[tool.poetry]
name = "aioci"
version = "0.2.0"
description = ""
authors = ["Jonas Krüger Svensson <jonas.svensson@intility.no>"]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
