wandb:
  enable: false
  project: ${project}
  name: ${name}
  entity: ${oc.env:USER}
savedir: ${oc.env:PWD}/saves/${name}
early_stopping:
  monitor: val_acc
  mode: max
debug: false
seed: 0
precision: 16
limit_val_batches: 1.0
batch_size: 100
grad_clip_norm: 10
collate_fn: auto
max_steps: 1000
log_every_n_steps: 100
val_check_interval: 100
gpus: 0
test_only: false
autoresume: false
ckpt_path: ${savedir}/latest.ckpt
learning_rate: 0.0001
val_sample_size: 100
name: ${model}-${suffix}
suffix: default
model: mymodel
project: wrangle-example-xor-clf
dhid: 300
