[tool.poetry]
name = "pyhelios"
version = "2.2.1"
description = "The Helios' toolbox"
license = "MIT"
authors = ["Julien Vanharen <julien.vanharen@gmail.com>"]
maintainers = ["Julien Vanharen <julien.vanharen@gmail.com>"]
readme = "README.md"
homepage = "https://pypi.org/project/pyhelios"
repository = "https://github.com/jvanhare/pyhelios"
documentation = "https://pypi.org/project/pyhelios"
keywords = [
    "Computational Fluid Dynamics",
    "Unstructured Mesh",
    "Anisotropic Mesh Adaptation",
    "High-Order RANS/LES",
    "HPC"
]
classifiers = [
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Intended Audience :: End Users/Desktop",
    "Intended Audience :: Science/Research",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Mathematics",
    "Topic :: Scientific/Engineering :: Physics",
    "Topic :: Scientific/Engineering :: Visualization",
    "Topic :: Software Development :: Version Control :: Git"
]
include = ["share/*"]

[tool.poetry.scripts]
pyhls = 'pyhelios.pyhls:app'

[tool.poetry.dependencies]
rich = "^10.0.0"
typer = "^0.4.0"
numpy = "^1.21.0"
jinja2 = "^3.0.0"
loguru = "0.5.3"
python = ">=3.7,<4.0.0"
ipython = "^7.0.0"
flatdict = "^4.0.0"
pytomlpp = "^1.0.0"
pygments = "^2.0.0"
traitlets = "^5.0.0"
xmltodict = "^0.12.0"
cmake-format = "^0.6.0"

[tool.poetry.dev-dependencies]
tox = "^3.24.0"
pytest = "^6.0.0"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]
