---
version: 1
disable_existing_loggers: false
#propagate: true
formatters:
    simple:
        format: '%(asctime)s %(name)-20s %(levelname)-8s %(message)s'
handlers:
    console:
        class: logging.StreamHandler
        level: INFO
        formatter: simple
        stream: ext://sys.stdout
loggers:
    snooze:
        level: INFO
        handlers: [console]
        propagate: false
