[build-system]
requires = [
    "setuptools>=51",
    "wheel"
]
build-backend = "setuptools.build_meta"

[project]
name = "pycurator"
version = "0.1b1"
description = "Collect data from popular data repositories with ease."
readme = "README.md"
requires-python = ">=3.10"
license = {file = "LICENSE.txt"}
keywords = ["curation", "API", "data collection"]
authors = [
  {email = "michaelbaluja@protonmail.com"},
  {name = "Michael Baluja"}
]
maintainers = [
  {name = "Michael Baluja", email = "michaelbaluja@protonmail.com"}
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Environment :: Console",
  "Intended Audience :: Science/Research",
  "License :: OSI Approved :: BSD License",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3.10",
  "Topic :: Scientific/Engineering"
]

dependencies = [
  "pandas",
  "requests",
  "scipy",
  "setuptools"
]

[project.optional-dependencies]
repositories = [
  "kaggle",
  "openml"
]
format = [
  "openpyxl"
]
test = [
  "pytest"
]

[project.urls]
repository = "https://github.com/michaelbaluja/PyCurator"

[project.entry-points."pycurator.cli"]
pycurator = "pycurator.cli:main"