#
# Magic Keys
#

DB_NAME='nauto'
DATE_COL='daily_ts'
DATE_UNIQ='serial_number'

TRACE=True

cAlias='|'
kAbove='above'
kAny='any'
kArgs='args'
kCast='as_number'
kCols='cols'
kCount='count'
kDoc='+doc'
kDrop='drop'
kExt='file_ext'
kFunc='function'
kGroup='group'
kIfNull='else'
kInner='inner'
kJoinType='join_type'
kKeepJoin='keep_join'
kKeepIndistinct='keep_indistinct'
kMatch='matching'
kOp='operator'
kColArg='$col'
kReverse='descend'
kRound='round'
kSave='save'
kSelect='select'
kSkip='skip'
kSkipSave='skip_save'
kSkipUpload='skip_upload'
kSort='sort'
kSQL='sql'
kUniq='ensure_unique'
kWhere='where'
