# Generated by Django 3.2 on 2022-05-06 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='user',
        ),
        migrations.AddField(
            model_name='login',
            name='username',
            field=models.TextField(default=''),
        ),
    ]
