# Generated by Django 3.2 on 2022-05-06 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20220505_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='username',
            field=models.TextField(default=''),
        ),
    ]
