# Generated by Django 3.2 on 2022-05-10 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alertmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertmessage',
            name='category',
            field=models.CharField(default='', max_length=25),
        ),
    ]
