# Template document for .yape config

# Get current python version (executing)
directory: .venv
requirements:
  - import: requirements.txt

environments:
  dev:
    requirements:
      - import: requirements.dev.txt
