[package]
authors = ["dmitry.dygalo <dadygalo@gmail.com>"]
description = "A crate for performing JSON schema validation"
edition = "2021"
exclude = ["tests", "python", "benches/data/*.json", ".github", ".yamllint", ".pre-commit-config.yaml", ".gitignore", ".gitmodules", "*.md"]
keywords = ["jsonschema", "validation"]
license = "MIT"
name = "jsonschema"
readme = "../README.md"
repository = "https://github.com/Stranger6667/jsonschema-rs"
version = "0.16.0"

categories = ["web-programming"]

[[bin]]
name = "jsonschema"

[features]
cli = ["structopt"]
default = ["resolve-http", "resolve-file", "cli"]
draft201909 = []
draft202012 = []

resolve-http = ["reqwest"]
resolve-file = []

[dependencies]
ahash = { version = "0.7.6", features = ["serde"] }
anyhow = "1.0.55"
base64 = "0.13.0"
bytecount = { version = "0.6.2", features = ["runtime-dispatch-simd"] }
fancy-regex = "0.10.0"
fraction = { version = "0.10.0", default-features = false, features = ["with-bigint"] }
iso8601 = "0.4.1"
itoa = "1.0.1"
lazy_static = "1.4.0"
memchr = "2.4.1"
num-cmp = "0.1.0"
parking_lot = "0.12.0"
percent-encoding = "2.1.0"
regex = "1.5.4"
reqwest = { version = "0.11.9", features = ["blocking", "json"], default-features = false, optional = true }
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
structopt = { version = "0.3.26", optional = true }
time = { version = "0.3.7", features = ["parsing", "macros"] }
url = "2.2.2"
uuid = "1.0.0"

[dev-dependencies]
bench_helpers = { path = "../bench_helpers" }
criterion = "0.3.5"
json_schema_test_suite = { version = "0.3.0", path = "../jsonschema-test-suite" }
jsonschema-valid = "0.4.0"
mockito = "0.31.0"
paste = "1.0.6"
test-case = "2.0.2"
valico = "3.6.0"

# Benchmarks for `jsonschema`
[[bench]]
harness = false
name = "jsonschema"

# Benchmarks for `valico`
[[bench]]
harness = false
name = "valico"

# Benchmarks for `jsonschema_valid`
[[bench]]
harness = false
name = "jsonschema_valid"

[profile.release]
codegen-units = 1
lto = "on"
