[tool.poetry]
name = "simple_downloader"
version = "0.1.2"
description = "A very simple downloader package with a visual indication."
authors = ["Kai Norman Clasen <k.clasen@protonmail.com>"]
license = "MIT license"
readme = "README.md"
homepage = "https://github.com/kai-tub/simple_downloader/"
repository = "https://github.com/kai-tub/simple_downloader/"

documentation = "https://github.com/kai-tub.github.io/simple_downloader"

include = [
    "LICENSE",
]

[tool.poetry.dependencies]
# TODO: Find a better way to set these values!
python = "^3.8"
pydantic = "^1.8"
tqdm = ">=4"
rich = ">=12"
requests = ">=2"
ipywidgets = "^7.6.0"

[tool.poetry.dev-dependencies]
black = "*"
isort = "*"
pytest = "*"
Sphinx = "^4.5"
furo = "*"
livereload = "*"
sphinx-external-toc = "*"
pre-commit = "*"
myst-nb = "0.14"
ipykernel = "*"
linkify-it-py = "*"

[tool.isort]
profile = "black"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
