separators:
  in_segment: '\n\n'
  in_sentence: '\n'
  out_segment: '\n\n'
  out_sentence: '\n'
merge:
  merge_lines: false
  merge_level: segment
  empty_lines_threshold: 0.6
  broken_lines_threshold: 0.4
split:
  keep_segment: true
  max_recover_step: 0
  max_recover_length: 30000
filter_language:
  filter: false
  detection_level: segment
  languages_to_keep:
    - en
    - ko
  min_language_probability: 0.8
filter_programming_language: false
filter_sentence_length:
  filter: false
  min_num_words: 3
  min_length: 10
chunk:
  chunk_size: 300
  chunk_overlap: false
return_as_list: false
print_args: false
verbose: ${oc.select:..verbose, true}
