[tool.poetry]
name = "tinamit-idm"
version = "0.2.2"
description = ""
authors = ["joelz575 <joel.harms@mail.mcgill.ca>"]

[tool.poetry.dependencies]
python = "^3.8"
trio = "^0.19.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
numpy = "^1.19.2"
tinamit = "2.0.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
