[tool.poetry]
name = "greatest_calculator_hits_vol_2"
version = "0.1.2"
description = "A very basic python calculator"
readme = "README_pypi.rst"
authors = ["heliossjr <helio.junior@loggi.com>"]
repository = "https://github.com/heliossjr/greatest_calculator_hits"
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7.1"

[tool.poetry.dev-dependencies]
pytest = "^7.1.1"
black = "^22.3.0"
mypy = "^0.942"
autopep8 = "^1.6.0"
flake8 = "^4.0.1"
pytest-cov = "^3.0.0"

[tool.autopep8]
max_line_length = 79

[tool.black]
line-length = 79

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
