
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-12T19:36:50-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "3f11dd20d5607b02cd2153dce325553f51843978",
 "version": "v0.1.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
