[tool.poetry]
name = "evpython"
version = "0.1.2"
description = ""
authors = ["Henrique Cunha"]
keywords = [
    "Environment Variables",
    "Encryption",
    "Sharing"
]

[tool.poetry.dependencies]
python = "^3.10"
pycryptodome = "^3.14.1"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
