[tool.poetry]
name = "maser4py"
version = "0.10.0"
description = "maser4py offers tools to handle low frequency radioastronomy data"
authors = ["Xavier BONNIN <xavier.bonnin@obspm.fr>","Baptiste CECCONI <baptiste.cecconi@obspm.fr>", "Sonny LION <sonny.lion@obspm.fr>", "Alan Loh <alan.loh@obspm.fr>", "Quynh Nhu Nguyen <quynh-nhu.nguyen@obspm.fr>"]
readme = "README.md"
license = "GPL-V3"
homepage = "https://pypi.org/project/maser4py"
repository = "https://github.com/maserlib/maser4py"
keywords = ["maser4py", "data science", "radioastronomy"]

[tool.poetry.urls]
"Documentation" = "https://maser.readthedocs.io/en/latest/"
"Tracker" = "https://github.com/maserlib/maser4py/issues"

[tool.poetry.dependencies]
python = ">=3.6.1"
astropy = "*"
scipy = "*"
numpy = "*"
toml = "*"
openpyxl = "*"
pytz = "*"
python-dateutil = "*"
jinja2 = "*"
spacepy = "^0.3"


[tool.poetry.dev-dependencies]
pytest = "^5.2"
pytest-cov = "2.10.1"
pytest-timeout = "^1.4"
pre-commit = "^2.8"

[tool.poetry.extras]
tests = ["pytest", "pytest-cov", "pytest-timeout"]

[[tool.poetry.packages]]
include = "maser"

[tool.black]
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.poetry.scripts]
maser = 'maser.script:main'


[build-system]
requires = ["poetry>=1.1.4", "setuptools"]
build-backend = "poetry.masonry.api"
