
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-10T04:53:58+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "20c20a1b450b467bae592c029cdef085061e9f98",
 "version": "1.16.0.post.dev493"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
