[build-system]
requires = ["setuptools>=51.1.2", "wheel", "Cython>=0.29.23,<3", "numpy>=1.20.3; python_version>='3.8'"]

# uncomment to enable pep517 after versioneer problem is fixed.
# https://github.com/python-versioneer/python-versioneer/issues/193
# build-backend = "setuptools.build_meta"