[tool.black]
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | env
  | venv
)/
'''
include = '\.pyi?$'
line-length = 79
target-version = ['py38', ]

[tool.isort]
profile = "black"
line_length = 79
skip_gitignore = true
filter_files = true

[tool.interrogate]
fail-under = 10
