[tool.poetry]
name = "hapi"
version = "1.0.5"
description = "Hydrological and Hydrodynamic modelling tool"
authors = ["Mostafa Farrag <moah.farag@gmail.com>"]

[[tool.poetry.source]]
name = "my-custom-repo"  # This name will be used in the configuration to retreive the proper credentials
url = "https://my.customrepo.com/simple/"  # URL used to download your packages from

[tool.poetry.dependencies]
python = ">=3.7.0,<3.10"
pandas = "<=1.3.2,<1.3.4"
numpy = ">=1.21.2,<1.21.4"
matplotlib = "=>3.4.2,<3.4.3"
scipy = ">=1.7.0,<1.7.2"
statsmodels = ">=0.12.2,<0.13.0"
netCDF4 = ">=1.5.5,<1.5.8"
scikit-learn = ">=0.24.2,<1.0.1"
scikit-image = "^0.18.3"
joblib = "^1.1.0"
ecmwf-api-client = "^1.6.1"
pyproj = "^3.2.1"
proj = "^0.2.0"
Shapely = "^1.8.0"
pytest = "^6.2.5"
Fiona = "^1.8.20"
geopandas = "^0.10.2"
rasterio = "^1.2.10"
rasterstats = "^0.16.0"
oasis = "^0.1.3"
ffmpeg-python = "^0.2.0"
gdal = ">=3.3.3,<3.4.1"
pre-commit = "^2.15.0"
geopy = "^2.2.0"


[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
# pytest-cov = "^2.12.1"

# coverage = {extras = ["toml"], version = "^5.4"}
# safety = "^1.10.3"
# mypy = "^0.910"
# typeguard = "^2.12.1"
# xdoctest = {extras = ["colors"], version = "^0.15.5"}
# pre-commit = "^2.13.0"
# flake8 = "^3.9.2"
# loguru = "^0.5.3"
# black = "^20.8b1"
# flake8-bandit = "^2.1.2"
# flake8-bugbear = "^21.4.3"
# flake8-docstrings = "^1.6.0"
# flake8-rst-docstrings = "^0.2.3"
# pep8-naming = "^0.12.0"
# darglint = "^1.8.0"
# reorder-python-imports = "^2.6.0"
# pre-commit-hooks = ">=3.4.0,<=4.0.1"

[tool.coverage.paths]
source = ["Hapi", "*/site-packages"]

[tool.coverage.run]
branch = true
source = ["gee_utils"]

[tool.coverage.report]
show_missing = true
# fail_under = 50

[tool.isort]
multi_line_output=3
include_trailing_comma=true
force_grid_wrap=0
use_parentheses=true
line_length=88
ensure_newline_before_comments=true
profile="black"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
# "--disable-pytest-warnings"
testpaths = [
    "tests",
]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
