[tool.poetry]
name = "pedroai"
version = "0.3.0"
description = ""
authors = ["Pedro Rodriguez <me@pedro.ai>"]

[tool.poetry.dependencies]
python = "^3.8"
plotnine = "^0.8"
requests = "^2.27.1"
pysimdjson = {extras = ["dev"], version = "^4.0.3"}
typer = "^0.4.0"
toml = "^0.10.2"
pydantic = "^1.9.0"
rich = "^12.4.1"
altair-saver = "^0.5.0"
altair = "^4.2.0"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
black = "^22.3.0"
pylint = "^2.13.8"
mypy = "^0.950"
isort = "^5.10.1"

[tool.poetry.scripts]
pedroai = "pedroai.main:cli"

[tool.isort]
known_first_party = "pedroai"
profile = "black"
multi_line_output = 3

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
