defaults:
  - /function: filter_length
  - /function/len_bytes: default
  - /function/len_words: default

apply_to: ${oc.select:..apply_to, text}
min_length: 3
max_length: 
len_func: len_bytes
verbose: ${oc.select:..verbose, true}
use_batcher: ${oc.select:..use_batcher, true}
