# This CI will lauch a Docker image that contains all the dependencies required
# within that image the pytest test suite is run 

name: CI with install

on:
  pull_request:
    branches:
      - develop
      - main
    paths-ignore:
      - 'docs/**'
      - '.gitignore'
      - '*.md'
      - 'CITATION.cff'
      - 'LICENSE.txt'
      - 'readthedocs.yml'

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: install package
        run: |
          pip install .

      - name: Run tests
        run: |
          ls
          pwd
          ls tests
          pip install .[tests]
          pytest tests -v --cov=dagmc_bounding_box --cov-append --cov-report term --cov-report xml

      - name: Upload to codecov
        uses: codecov/codecov-action@v2
