
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-10T20:50:11-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "db803cc99447da59d4a5cecaa1d58b0244dcc38b",
 "version": "3.5.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
