[tool.poetry]
name = "nautobot_utsc"
version = "2022.5.10.1"
description = "A collection of UTSC-specific modifications and extensions to Nautobot."
authors = ["Alex Tremblay <alex.tremblay@utoronto.ca>", "University of Toronto Governing Council <governing.council@utoronto.ca>"]
license = "MIT"
packages = [
  { include = "nautobot_utsc", from = "src_"}
]


# [tool.poetry.scripts]

[tool.poetry.dependencies]
python = ">=3.10,<4.0"
nautobot_ssot = ">=1.1.0"
"utsc.core" = "*"
nautobot = ">=1.3"
django-auth-ldap = "*" 
debugpy = "*"
django-debug-toolbar = "*"
html-table-parser-python3 = ">=0.2.0"
django-environ = "*"



[tool.poetry.dev-dependencies]
"utsc.core" = {path = "../core"}
django-environ = {git = "https://github.com/alextremblay/django-environ", rev = "main"}

[tool.poe.tasks]
run.cmd = "nautobot-server"
run.env   = { NAUTOBOT_ROOT = "./dev_data", ENV_PATH = "${NAUTOBOT_ROOT}/.env"}
start.cmd = "poe run start --ini dev_data/uwsgi.ini"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
