# This file was generated by mettle.genes.db.GenPy3 [ver 2.1] on Tue Mar 22 16:51:11 2022
#

import copy
import datetime
import uuid
import time
import mettle.lib
import mettle.io
import mettle.db

from .job_key import tJobKey

class tJob(mettle.io.ISerializable, mettle.db.IPrimaryKey):

    def __init__(self,
                 id: int = 0,
                 name: str = '',
                 group_id: str = '',
                 program_path: str = '',
                 program_args: str = '',
                 priority: int = 0,
                 stamp_by: str = ''):
        """
        Constructor.

        :param id: int
        :param name: str
        :param group_id: str
        :param program_path: str
        :param program_args: str
        :param priority: int
        :param stamp_by: str
        :param stamp_tm: datetime.datetime
        """
        self.id = id
        self.name = name
        self.group_id = group_id
        self.program_path = program_path
        self.program_args = program_args
        self.priority = priority
        self.stamp_by = stamp_by
        self.stamp_tm = None

    def clear(self):
        """
        Clears all member variables for this database record.
        """
        self.id = 0
        self.name = ''
        self.group_id = ''
        self.program_path = ''
        self.program_args = ''
        self.priority = 0
        self.stamp_by = ''
        self.stamp_tm = None

    def _name(self) -> str:
        """
        Name of the record.

        :return: The name.
        """
        return 'tJob'

    def _serialize(self, _w: mettle.io.IWriter, _oname: str = None):
        """
        Serialize record to a stream.

        :param _w:
        :param _oname:
        """
        if _oname == None:
            _oname = self._name()

        _w.write_start(_oname)
        _w.write_int64("id", self.id)
        _w.write_string("name", self.name)
        _w.write_string("group_id", self.group_id)
        _w.write_string("program_path", self.program_path)
        _w.write_string("program_args", self.program_args)
        _w.write_int32("priority", self.priority)
        _w.write_string("stamp_by", self.stamp_by)
        _w.write_datetime("stamp_tm", self.stamp_tm)
        _w.write_end(_oname)

    def _deserialize(self, _r: mettle.io.IReader, _oname: str = None):
        """
        Deserialize record from a stream.

        :param _r:
        :param _oname:
        """
        if _oname == None:
            _oname = self._name()

        _r.read_start(_oname)
        self.id = _r.read_int64("id")
        self.name = _r.read_string("name")
        self.group_id = _r.read_string("group_id")
        self.program_path = _r.read_string("program_path")
        self.program_args = _r.read_string("program_args")
        self.priority = _r.read_int32("priority")
        self.stamp_by = _r.read_string("stamp_by")
        self.stamp_tm = _r.read_datetime("stamp_tm")
        _r.read_end(_oname)

    def _copy_from(self, rec: "tJob"):
        """
        Copies the column from the rec into this record.

        :param rec: The source record.
        """
        self.id = rec.id
        self.name = rec.name
        self.group_id = rec.group_id
        self.program_path = rec.program_path
        self.program_args = rec.program_args
        self.priority = rec.priority
        self.stamp_by = rec.stamp_by
        self.stamp_tm = rec.stamp_tm

    def _write_pk(self, _key: "tJob"):
        """
        Write the primary key columns to the key object.

        :param _key:
        """
        self._write_key(_key)

    def _read_pk(self, _key: "tJob"):
        """
        Read the primary key columns from the key object.

        :param _key:
        """
        self._read_key(_key)

    def _serialize_key(self, _w: mettle.io.IWriter):
        """
        Serialize the primary key to a stream.

        :param _w:
        """
        _key = tJobKey()

        self._write_key(_key)
        _key._serialize(_w)

    def _deserialize_key(self, _r: mettle.io.IReader):
        """
        Deserialize the primary key from a stream.

        :param _r:
        """
        _key = tJobKey()

        _key._deserialize(_r)
        self._read_key(_key)

    @staticmethod
    def _cache_davs(dvc=None, for_ins: bool = False, key_only: bool = False):
        """
        Cache the DAV into the dav cache (or create one) and return it.

        :param dvc: (mettle.lib.DavCache), target cache, if None a new one is created and returned.
        :param for_ins: Davs for insert.
        :param key_only: Davs by key only, ie for delete/selectone.
        """
        if dvc is None:
            dvc = mettle.lib.DavCache()

        if not for_ins:
            dvc.add_targ("id", mettle.lib.Dav(mettle.lib.Dav.eDavType.Min, 1))
            dvc.add_targ("id", mettle.lib.Dav(mettle.lib.Dav.eDavType.NotNull))

        if key_only:
            return dvc

        dvc.add_targ("name", mettle.lib.Dav(mettle.lib.Dav.eDavType.NotNull))
        dvc.add_targ("name", mettle.lib.Dav(mettle.lib.Dav.eDavType.Max, 256))
        dvc.add_targ("group_id", mettle.lib.Dav(mettle.lib.Dav.eDavType.NotNull))
        dvc.add_targ("group_id", mettle.lib.Dav(mettle.lib.Dav.eDavType.Max, 128))
        dvc.add_targ("program_path", mettle.lib.Dav(mettle.lib.Dav.eDavType.NotNull))
        dvc.add_targ("program_path", mettle.lib.Dav(mettle.lib.Dav.eDavType.Max, 256))
        dvc.add_targ("program_args", mettle.lib.Dav(mettle.lib.Dav.eDavType.Max, 256))
        dvc.add_targ("priority", mettle.lib.Dav(mettle.lib.Dav.eDavType.NotNull))
        dvc.add_targ("priority", mettle.lib.Dav(mettle.lib.Dav.eDavType.In, [1,10,20]))
        dvc.add_targ("stamp_by", mettle.lib.Dav(mettle.lib.Dav.eDavType.NotNull))
        dvc.add_targ("stamp_by", mettle.lib.Dav(mettle.lib.Dav.eDavType.Max, 128))

        return dvc

    def _get_davs(self, dvc=None, for_ins: bool = False, key_only: bool = False):
        tJob._cache_davs(dvc, for_ins, key_only)

    def _write_key(self, _key: tJobKey):
        """
        Write primary key columns to _key.

        :param _key:
        """
        _key.id = self.id

    def _read_key(self, _key: tJobKey):
        """
        Read the primary key columns from _key.

        :param _key:
        """
        self.id = _key.id

    class Priority_Couplet(dict):
        key_highest = 1
        key_normal = 10
        key_lowest = 20

        value_highest = "Highest"
        value_normal = "Normal"
        value_lowest = "Lowest"

        def __init__(self):
            self[self.key_highest] = self.value_highest
            self[self.key_normal] = self.value_normal
            self[self.key_lowest] = self.value_lowest

        @staticmethod
        def get_value(key):
            if key == tJob.Priority_Couplet.key_highest:
                return tJob.Priority_Couplet.value_highest

            if key == tJob.Priority_Couplet.key_normal:
                return tJob.Priority_Couplet.value_normal

            if key == tJob.Priority_Couplet.key_lowest:
                return tJob.Priority_Couplet.value_lowest

            return ""

    @staticmethod
    def _pk_compare(x, y) -> int:
        """
        Compare function do primary key comparisons for list sorts and searches.

        :return: zero for x == y, negative for x < y, positive for x > y
        """
        return x.id - y.id

    def __lt__(self, other):
        return other and self._pk_compare(self, other) < 0

    def __gt__(self, other):
        return other and self._pk_compare(self, other) > 0

    def __eq__(self, other):
        return other and self._pk_compare(self, other) == 0

    def __le__(self, other):
        return other and self._pk_compare(self, other) <= 0

    def __ge__(self, other):
        return other and self._pk_compare(self, other) >= 0

    def __ne__(self, other):
        return other == None or self._pk_compare(self, other)

    def __repr__(self) -> str:
        return '<Job [id:%r, name:%.32s, group_id:%.32s, program_path:%.32s, program_args:%.32s, priority:%r, stamp_by:%.32s, stamp_tm:%s]>' % (
            self.id, self.name, self.group_id, self.program_path, self.program_args, self.priority, self.stamp_by, self.stamp_tm)


    class List(list, mettle.io.ISerializable):
        """
        List Class
        """

        def _name(self) -> str:
            """
            Name of the list.

            :return: The name
            """
            return 'tJob.List'

        def _serialize(self, _w: mettle.io.IWriter, _oname: str = None):
            """
            Serialize the list to a stream.

            :param _w:
            :param _oname:
            """
            if _oname == None:
                _oname = self._name()

            _w.write_start_list(_oname, len(self))

            for _rec in self:
                _rec._serialize(_w)

            _w.write_end(_oname)

        def _deserialize(self, _r: mettle.io.IReader, _oname: str = None):
            """
            Deserialize the list from a stream.

            :param _r:
            :param _oname:
            """
            if _oname == None:
                _oname = self._name()

            _cnt = _r.read_start_list(_oname)

            while _cnt >= 1:
                _rec  = tJob()
                _cnt -= 1
                _rec._deserialize(_r)
                self.append(_rec)

            _r.read_end(_oname)

        def __repr__(self) -> str:
            return '<tJob.List[%d]>' % (len(self))

        def _get_davs(self, dvc=None, for_ins: bool = False, key_only: bool = False):
            return tJob._cache_davs(dvc, for_ins, key_only)

