# This file was generated by mettle.genes.db.GenPy3 [ver 2.1] on Tue Mar 22 16:51:11 2022
#

import copy
import datetime
import uuid
import time
import mettle.lib
import mettle.io
import mettle.db

from .batch import tBatch
from .batch_inst import tBatchInst

class oBatchWithLatestInst(mettle.io.ISerializable):

    def __init__(self,
                 brec: tBatch = None,
                 irec: tBatchInst = None):
        """
        Constructor.

        :param brec: table -> table:this
        :param irec: table -> table:BatchInst
        """
        self.brec = tBatch()
        if brec:
            self.brec._copy_from(brec)
        self.irec = tBatchInst()
        if irec:
            self.irec._copy_from(irec)

    def clear(self):
        """
        Clears all member variables for this database record.
        """
        self.brec.clear()
        self.irec.clear()

    def _name(self) -> str:
        """
        Name of the record.

        :return: The name.
        """
        return 'oBatchWithLatestInst'

    def _serialize(self, _w: mettle.io.IWriter, _oname: str = None):
        """
        Serialize record to a stream.

        :param _w:
        :param _oname:
        """
        if _oname == None:
            _oname = self._name()

        _w.write_start(_oname)
        self.brec._serialize(_w)
        self.irec._serialize(_w)
        _w.write_end(_oname)

    def _deserialize(self, _r: mettle.io.IReader, _oname: str = None):
        """
        Deserialize record from a stream.

        :param _r:
        :param _oname:
        """
        if _oname == None:
            _oname = self._name()

        _r.read_start(_oname)
        self.brec._deserialize(_r)
        self.irec._deserialize(_r)
        _r.read_end(_oname)

    def _copy_from(self, rec: "oBatchWithLatestInst"):
        """
        Copies the column from the rec into this record.

        :param rec: The source record.
        """
        self.brec._copy_from(rec.brec)
        self.irec._copy_from(rec.irec)

    def __repr__(self) -> str:
        return '<Batch [brec:%r, irec:%r]>' % (
            self.brec, self.irec)


    class List(list, mettle.io.ISerializable):
        """
        List Class
        """

        def _name(self) -> str:
            """
            Name of the list.

            :return: The name
            """
            return 'oBatchWithLatestInst.List'

        def _serialize(self, _w: mettle.io.IWriter, _oname: str = None):
            """
            Serialize the list to a stream.

            :param _w:
            :param _oname:
            """
            if _oname == None:
                _oname = self._name()

            _w.write_start_list(_oname, len(self))

            for _rec in self:
                _rec._serialize(_w)

            _w.write_end(_oname)

        def _deserialize(self, _r: mettle.io.IReader, _oname: str = None):
            """
            Deserialize the list from a stream.

            :param _r:
            :param _oname:
            """
            if _oname == None:
                _oname = self._name()

            _cnt = _r.read_start_list(_oname)

            while _cnt >= 1:
                _rec  = oBatchWithLatestInst()
                _cnt -= 1
                _rec._deserialize(_r)
                self.append(_rec)

            _r.read_end(_oname)

        def __repr__(self) -> str:
            return '<oBatchWithLatestInst.List[%d]>' % (len(self))

