# Generated by Django 3.2.12 on 2022-04-29 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_forms', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CaptchaField',
        ),
        migrations.AlterField(
            model_name='formentry',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
