hydra:
  run:
    dir: ${savedir}
  sweep:
    dir: ${savedir}/sweep
    subdir: ${hydra.job.num}
  launcher:
    submitit_folder: ${savedir}/submitit
    timeout_min: 4320
    cpus_per_task: 8
    gpus_per_node: 1
    tasks_per_node: 1
    mem_gb: 64
    nodes: 1
    name: ${project}
    _target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
    partition: learnlab
    comment: null
    constraint: null
    exclude: null
    cpus_per_gpu: null
    gpus_per_task: null
    mem_per_gpu: null
    mem_per_cpu: null
    signal_delay_s: 120
    max_num_timeout: 0
    additional_parameters: {}
    array_parallelism: 256
    setup: null
  sweeper:
    _target_: hydra._internal.core_plugins.basic_sweeper.BasicSweeper
    max_batch_size: null
  help:
    app_name: ${hydra.job.name}
    header: '${hydra.help.app_name} is powered by Hydra.

      '
    footer: 'Powered by Hydra (https://hydra.cc)

      Use --hydra-help to view Hydra specific help

      '
    template: '${hydra.help.header}

      == Configuration groups ==

      Compose your configuration from those groups (group=option)


      $APP_CONFIG_GROUPS


      == Config ==

      Override anything in the config (foo.bar=value)


      $CONFIG


      ${hydra.help.footer}

      '
  hydra_help:
    template: 'Hydra (${hydra.runtime.version})

      See https://hydra.cc for more info.


      == Flags ==

      $FLAGS_HELP


      == Configuration groups ==

      Compose your configuration from those groups (For example, append hydra/job_logging=disabled
      to command line)


      $HYDRA_CONFIG_GROUPS


      Use ''--cfg hydra'' to Show the Hydra config.

      '
    hydra_help: ???
  hydra_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][HYDRA] %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
    root:
      level: INFO
      handlers:
      - console
    loggers:
      logging_example:
        level: DEBUG
    disable_existing_loggers: false
  job_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][%(name)s][%(levelname)s] - %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
      file:
        class: logging.FileHandler
        formatter: simple
        filename: ${hydra.job.name}.log
    root:
      level: INFO
      handlers:
      - console
      - file
    disable_existing_loggers: false
  env: {}
  searchpath: []
  callbacks: {}
  output_subdir: .hydra
  overrides:
    hydra:
    - hydra/launcher=slurm
    - hydra.launcher.partition=learnlab
    task:
    - wandb.enable=true
    - model.name=multi
    - env.name=rtfm_train_s1-v0,msgr_train-all_s1-v0
    - suffix=1,2,3,4,5,6,7,8
    - project=silg-moolib
  job:
    name: ${name}
    override_dirname: env.name=rtfm_train_s1-v0,msgr_train-all_s1-v0,model.name=multi,project=silg-moolib,suffix=1,2,3,4,5,6,7,8,wandb.enable=true
    id: ???
    num: ???
    config_name: default
    env_set:
      OMP_NUM_THREADS: '1'
      RAY_OBJECT_STORE_ALLOW_SLOW_STORAGE: '1'
    env_copy: []
    config:
      override_dirname:
        kv_sep: '='
        item_sep: ','
        exclude_keys: []
  runtime:
    version: 1.1.1
    cwd: /private/home/vzhong/projects/wrangl/wrangl/examples/learn/silg_rl
    config_sources:
    - path: hydra.conf
      schema: pkg
      provider: hydra
    - path: /private/home/vzhong/projects/wrangl/wrangl/examples/learn/silg_rl/conf
      schema: file
      provider: main
    - path: ''
      schema: structured
      provider: schema
    choices:
      hydra/env: default
      hydra/callbacks: null
      hydra/job_logging: default
      hydra/hydra_logging: default
      hydra/hydra_help: default
      hydra/help: default
      hydra/sweeper: basic
      hydra/launcher: slurm
      hydra/output: default
  verbose: false
name: ${env.name}-${model.name}-${suffix}
suffix: default
model:
  name: multi
  use_local_conv: false
  use_grid_attn: false
  field_attn: false
  stateful: false
  num_film: 5
  demb: 100
  drnn: 200
  drep: 400
env:
  name: silg:rtfm_train_s1-v0
  time_penalty: -0.02
project: silg-moolib
peer: 0
wandb:
  enable: true
  project: ${project}
  name: ${name}
  entity: ${oc.env:USER}
savedir: ${oc.env:PWD}/saves/${name}
localdir: ${savedir}/peers/${peer}
local_name: ${name}-${peer}
ckpt_path: ${savedir}/latest.ckpt
debug: false
max_steps: 100000000
autoresume: false
device: cuda:0
actor_batch_size: 256
baseline_cost: 0.5
batch_size: 64
connect: 100.97.69.72:4431
discounting: 0.99
entropy_cost: 0.05
grad_clip_norm: 40
log_fmt: '[%(levelname)s:${name} %(module)s:%(lineno)d %(asctime)s] %(message)s'
log_interval: 10
checkpoint_interval: 600
num_actor_batches: 2
num_actor_cpus: 4
optimizer:
  learning_rate: 0.0005
  alpha: 0.99
  momentum: 0
  epsilon: 0.01
unroll_length: 20
virtual_batch_size: 256
reward_clip: 1.0
warmup: 0
