[tool.poetry]
name = "deciphon-api"
version = "0.3.1"
description = "RESTful API for Deciphon scheduler"

license = "MIT"

authors = ["Danilo Horta <danilo.horta@pm.me>"]

readme = "README.md"

repository = "https://github.com/EBI-Metagenomics/deciphon-api"
homepage = "https://github.com/EBI-Metagenomics/deciphon-api"

keywords = ["deciphon", "api"]

classifiers = ["License :: OSI Approved :: MIT License"]

include = [
  { path = "deciphon_api/sched/*.so", format = "wheel" },
  { path = "deciphon_api/sched/*.pyd", format = "wheel" },
  { path = "build_ext_deps", format = "sdist" },
  { path = ".env.example" },
]

[tool.poetry.dependencies]
bcbio-gff = "*"
biopython = "*"
build = "*"
cffi = "*"
fastapi = "*"
loguru = "*"
pooch = "*"
pydantic = { extras = ["dotenv"], version = "*" }
python = "^3.8"
python-multipart = "*"
toml = "^0.9"
typer = "*"
uvicorn = { extras = ["uvloop", "httptools"], version = "*" }
xxhash = "*"

[tool.poetry.dev-dependencies]
black = "*"
isort = "*"
pyright = "*"
pytest = "*"
requests = "*"
coverage = "*"
pytest-cov = "*"

[tool.poetry.build]
script = "build_ext.py"
generate-setup-file = false

[tool.poetry.scripts]
deciphon-api = "deciphon_api.console:run"

[build-system]
requires = ["poetry_core>=1.0.0", "cffi"]
build-backend = "poetry.core.masonry.api"

[tool.cibuildwheel]
skip = "cp36-* cp37-* pp*"

[tool.pytest.ini_options]
addopts = "--cov=deciphon_api --cov-report html"
testpaths = ["tests"]
