[plot]

[plot.y]
format = "pdf"
legend_position = "north west"
xlabel = "$x$ $[-]$"
ylabel = "$\\alpha$ $[-]$"
[[plot.y.lines]]
data = ["dataset.dat", "0", "1"]
label = "$y$"
style = "k-"


[plot.z]
format = "pdf"
legend_position = "north west"
xlabel = "$x$ $[-]$"
ylabel = "$\\alpha$ $[-]$"
[[plot.z.lines]]
data = ["dataset.dat", "0", "2"]
label = "$z$"
style = "k-"

[plot.yz]
format = "pdf"
legend_position = "north west"
xlabel = "$x$ $[-]$"
ylabel = "$\\alpha$ $[-]$"
[[plot.yz.lines]]
data = ["dataset.dat", "0", "1"]
label = "$y$"
style = "r-ow"
[[plot.yz.lines]]
data = ["dataset.dat", "0", "2"]
label = "$z$"
style = "b-sw"
