defaults:
  - /function: general_function
  - /_call_: replace

apply_to: ${oc.select:..apply_to, ''}
parameters:
  to_replace:
  value:
  limit:
  regex: false
  method:
verbose: ${oc.select:..verbose, true}
