[tool.black]
line-length = 80

[tool.isort]
profile = "black"

[tool.pylint.MASTER]
# Use multiple processes to speed up Pylint. Specifying 0 will auto-detect the
# number of processors available to use.
jobs = 0

[tool.pylint.'MESSAGES CONTROL']
disable=[
  "missing-function-docstring",
  "missing-class-docstring",
  "missing-module-docstring",
]

[tool.pylint.FORMAT]
max-line-length=80
