name: Publish visu3d to PyPI

on:
  # Event manually triggered (in the Github UI)
  workflow_dispatch:
    inputs:
      git-ref:
        description: Git ref (e.g. SHA or tag) (Optional)
        default: ""
        required: false

jobs:
  publish-job:
    if: github.repository == 'google-research/visu3d'  # prevents action from running on forks
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.git-ref }}

    # Setup Python
    - uses: actions/setup-python@v2
      with:
        python-version: 3.7

    # Publish the package
    - uses: etils-actions/pypi-build-publish@v1
      with:
        pypi-token: ${{ secrets.PYPI_API_TOKEN }}
