# SPDX-FileCopyrightText: 2020 Diego Elio Pettenò
#
# SPDX-License-Identifier: Unlicense

repos:
-   repo: https://github.com/python/black
    rev: 22.3.0
    hooks:
    - id: black
      args: ['--force-exclude', '^(.*/)?fluxvis/greaseweazle(/.*)$|^(.*/)?a2rchery\.py$']
-   repo: https://github.com/fsfe/reuse-tool
    rev: v0.12.1
    hooks:
    - id: reuse
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
-   repo: https://github.com/pycqa/pylint
    rev: v2.11.1
    hooks:
    -   id: pylint
        name: pylint (library code)
        types: [python]
        exclude: "^(docs/|examples/|tests/|fluxvis/greaseweazle/|setup.py|fluxvis/a2rchery.py$)"
