[tool.poetry]
name = "pip-compile-cross-platform"
version = "0.9.0"
description = ""
authors = ["Mitchell Hentges <mitch9654@gmail.com>"]
packages = [{include = "pip_compile_cross_platform"}]

[tool.poetry.dependencies]
python = "^3.7"
poetry = "^1.2.0b1"
pip-requirements-parser = "^31.2.0"

[tool.poetry.dev-dependencies]
black = "^22.3.0"
pyupgrade = "^2.32"
flake8 = "^4.0"
mypy = "0.942"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
