# Generated by Django 3.2.13 on 2022-05-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template_data', '0002_auto_20220418_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatedata',
            name='lang',
            field=models.CharField(blank=True, choices=[('fr', 'Francais'), ('en', 'English')], max_length=100, null=True),
        ),
    ]
