[tool.poetry]
name = "supermodels"
version = "0.1.12"
description = ""
authors = ["Tsvetan Kintisheff <kintisheff@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
python-dateutil = "^2.8.2"

[tool.poetry.dev-dependencies]
pytest = "6.2.5"
flake8 = "^4.0.1"
flake8-bugbear = "^21.9.2"
flake8-builtins = "^1.5.3"
flake8-comprehensions = "^3.7.0"
flake8-docstrings = "^1.6.0"
pre-commit = "^2.15.0"
safety = "^1.10.3"
hypothesis = "^6.24.0"
freezegun = "^1.1.0"
coverage = "^6.1.2"
bandit = "^1.7.4"

[build-system]
requires = ["poetry-core>=1.0.7"]
build-backend = "poetry.core.masonry.api"
