[tool.poetry]
name = "testfolio"
version = "0.1.0"
description = "Quick portfolio backtesting using historical market data"
authors = ["Bradley He <bhe6001@gmail.com>"]
repository = "https://github.com/BradleyHe/testfolio"
keywords = ["portfolio", "stock", "backtest", "finance"]
license = "MIT"
readme = "README.md"
classifiers = [
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Topic :: Office/Business :: Financial"
]

[tool.poetry.dependencies]
python = "^3.6"
yfinance = ">= 0.1.70"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
