[tool.poetry]
name = "testfolio"
version = "0.1.0a0"
description = "Library that backtests a given portfolio's asset allocation using historical market data from Yahoo."
authors = ["Bradley He <bhe6001@gmail.com>"]
repository = "https://github.com/BradleyHe/testfolio"
keywords = ["portfolio", "stock", "backtest", "finance"]
license = "MIT"
readme = "README.md"
classifiers = [
    "Operating System :: OS Independent",
]

[tool.poetry.dependencies]
python = "^3.7"
yfinance = ">= 0.1.70"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
