# Generated by Django 3.2.12 on 2022-04-29 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listgroup', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listgroup',
            options={'verbose_name': 'Listen-Gruppe'},
        ),
        migrations.AlterModelOptions(
            name='listgroupitem',
            options={'verbose_name': 'Listen-Eintrag'},
        ),
    ]
