variables:
    RELEASE_NAME: "${CI_PROJECT_NAME}-${CI_COMMIT_REF_SLUG}-g${CI_COMMIT_SHORT_SHA}-b${CI_PIPELINE_ID}"

include:
  - project: "devops/support"
    ref: master
    file:
      - "includes/variables/pypi-gitlab.yml"
      - "includes/build/rust/crates-io-mirror.yml"
      - "includes/reports/pytest-junit.yml"
      - "includes/docs/python-pdoc.yml"

default:
    tags:
      - linux-docker
    image: ${PLG_CI_DOCKER_TAG}/rusty-python:latest

stages:
  - check
  - build
  - test
  - wheels
  - publish-test
  - install-test
  - deploy

fmt:
    stage: check
    script:
      - cargo fmt -- --check

clippy:
    stage: check
    script:
      - cargo clippy -- --deny warnings

compile:
    stage: build
    script:
      - cargo build --release
      - mkdir -p dist
      - cp "target/release/lib${CI_PROJECT_NAME}.so" "dist/${CI_PROJECT_NAME}.so"
    artifacts:
        name: "${RELEASE_NAME}-bin-lin64"
        paths:
          - dist

compile-win64:
    stage: build
    script:
      - cargo build --release --target x86_64-pc-windows-gnu
      - mkdir -p dist
      - cp "target/x86_64-pc-windows-gnu/release/${CI_PROJECT_NAME}.dll" "dist/${CI_PROJECT_NAME}.pyd"
    artifacts:
        name: "${RELEASE_NAME}-bin-win64"
        paths:
          - dist

package:
    stage: wheels
    script:
      - maturin build --release --strip
      - cp -t dist target/wheels/*.whl
    artifacts:
        name: "${RELEASE_NAME}-wheel-lin64"
        paths:
          - dist

package-win64:
    stage: wheels
    script:
      - maturin build -i python3 --release --target x86_64-pc-windows-gnu
      - cp -t dist target/wheels/*.whl
    artifacts:
        name: "${RELEASE_NAME}-wheel-win64"
        paths:
          - dist

package-sdist:
    stage: wheels
    script:
      - maturin sdist
      - cp -t dist target/wheels/*.tar.gz
    artifacts:
        name: "${RELEASE_NAME}-sdist"
        paths:
          - dist

typecheck:
    stage: test
    script:
      - python3 -m venv --system-site-packages mypy_venv
      - . mypy_venv/bin/activate
      - maturin develop
      - python3 -m pylint tests
      - python3 -m mypy tests

runtests:
    stage: test
    variables:
        PIP_INDEX_URL: "${PLG_CI_PYPI_INDEX_URL}"
    script:
      - tox

pubtest:
    stage: publish-test
    script:
      - maturin upload --skip-existing -r "${PYPI_SERVER}" -u "${PYPI_USER}" -p "${PYPI_PASSWORD}" dist/*.whl dist/*.tar.gz

test-install:
    stage: install-test
    image: ${PLG_CI_DOCKER_TAG}/python:latest
    script:
      - pip3 install "${CI_PROJECT_NAME}" --index-url "${PYPI_INDEX_URL}"
      - python3 -m unittest

test-install-win64:
    stage: install-test
    tags:
      - windows-docker
    image: ${PLG_CI_DOCKER_TAG}/python_2004:latest
    variables:
        ErrorActionPreference: stop
    script:
      - pip3 install "${CI_PROJECT_NAME}" --index-url "${PYPI_INDEX_URL}"
      - python -m unittest

test-install-sdist:
    stage: install-test
    image: ${PLG_CI_DOCKER_TAG}/rusty-python:latest
    script:
      - pip3 install "${CI_PROJECT_NAME}" --no-binary "${CI_PROJECT_NAME}" --index-url "${PYPI_INDEX_URL}"
      - python3 -m unittest

publish-wheels:
    stage: deploy
    only:
      - tags
    script:
      - maturin upload -r "${PLG_CI_PYPI_SERVER}" -u "${PLG_CI_PYPI_USER}" -p "${PLG_CI_PYPI_PASSWORD}" dist/*.whl dist/*.tar.gz
