[tool.poetry]
name = "hyperupcall"
version = "0.1.0"
description = ""
license = "BSD-3-Clause"
authors = ["Edwin Kofler <edwin@kofler.dev>"]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
