[tool.poetry]
name = "wafflehacks-mailer"
version = "0.2.1"
description = "The Python SDK for the WaffleHacks mailer"
readme = "./README.md"
authors = ["Alex Krantz <alex@krantz.dev>"]

packages = [
    { include = "mailer" }
]

[tool.poetry.dependencies]
python = "^3.8"
aiohttp = {version = "^3.8.1", extras = ["speedups"]}
requests = "^2.27.1"

[tool.poetry.dev-dependencies]
black = "^22.1.0"
ipython = "^8.1.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
