[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "oc_sprint_datetime"
authors = [{name = "0x29a", email = "nk0d6bxt@anonaddy.me"}]
license = {file = "LICENSE"}
readme = "README.md"
classifiers = ["License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)"]
dynamic = ["version", "description"]
requires-python = ">=3.8"
dependencies = [
  "jira==3.2.0",
  "python-dotenv==0.20.0", 
]

[project.urls]
Home = "https://github.com/0x29a/oc_sprint_datetime"
