---
- name: my postgresql instances
  hosts: localhost
  tasks:
    - name: production instance
      dalibo.pglift.instance:
        name: prod
        port: 5433
        state: started
        ssl: true
        configuration:
          max_connections: 100
          shared_buffers: 1GB
          unix_socket_directories: /tmp
        prometheus_port: 9186
        surole_password: "{{ postgresql_surole_password }}"
        extensions:
          - unaccent
      register: prod

    - name: db, dropped
      community.postgresql.postgresql_db:
        name: db
        state: absent
        login_host: "{{ prod.env.PGHOST }}"
        login_port: "{{ prod.env.PGPORT }}"
      environment: "{{ prod.env }}"

    - name: bob, dropped
      dalibo.pglift.role:
        instance: prod
        name: bob
        state: absent

    - name: pre-production instance, now dropped
      dalibo.pglift.instance:
        name: preprod
        state: absent

    - name: dev instance, started, with SSL
      dalibo.pglift.instance:
        name: dev
        port: 5455
        state: started
        ssl: true
        configuration:
          max_connections: 42
          unix_socket_directories: /tmp
        prometheus_port: 9189
        surole_password: "{{ postgresql_surole_password }}"
