
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-13T19:39:57+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "2fdeec0c7f1b50ecb4b000b495c5d4e739c0816a",
 "version": "0.2.0.post0.dev41"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
