
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-11T04:27:34+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "8c626abfdfe9ab23c787f82fa836eeb909c6d6d8",
 "version": "1.16.0.post.dev497"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
