# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: entity_reference.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x65ntity_reference.proto\x12\x14\x63\x61lixa.domain.entity\x1a\x0c\x63ommon.proto\"\xb7\x01\n\x0f\x45ntityReference\x12\x17\n\x0forganization_id\x18\x01 \x01(\t\x12\x36\n\nexternalId\x18\x02 \x01(\x0b\x32 .calixa.domain.common.ExternalIdH\x00\x12\x16\n\x0c\x63\x61nonical_id\x18\x03 \x01(\tH\x00\x12\x35\n\x0b\x65ntity_type\x18\x04 \x01(\x0e\x32 .calixa.domain.common.EntityTypeB\x04\n\x02idB\x1d\n\x17io.calixa.domain.entityH\x01P\x01\x62\x06proto3')



_ENTITYREFERENCE = DESCRIPTOR.message_types_by_name['EntityReference']
EntityReference = _reflection.GeneratedProtocolMessageType('EntityReference', (_message.Message,), {
  'DESCRIPTOR' : _ENTITYREFERENCE,
  '__module__' : 'entity_reference_pb2'
  # @@protoc_insertion_point(class_scope:calixa.domain.entity.EntityReference)
  })
_sym_db.RegisterMessage(EntityReference)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\027io.calixa.domain.entityH\001P\001'
  _ENTITYREFERENCE._serialized_start=63
  _ENTITYREFERENCE._serialized_end=246
# @@protoc_insertion_point(module_scope)
