# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: integration_elt.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import field_mask_pb2 as google_dot_protobuf_dot_field__mask__pb2
import entity_pb2 as entity__pb2
import common_pb2 as common__pb2
import integration_source_pb2 as integration__source__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15integration_elt.proto\x12\x16\x63\x61lixa.integration.elt\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a google/protobuf/field_mask.proto\x1a\x0c\x65ntity.proto\x1a\x0c\x63ommon.proto\x1a\x18integration_source.proto\"\x98\x02\n\x0f\x45xtractedEntity\x12\x17\n\x0forganization_id\x18\x01 \x01(\t\x12\x13\n\x0binstance_id\x18\x02 \x01(\t\x12\x1e\n\x16\x64\x61ta_warehouse_sync_id\x18\x0b \x01(\t\x12<\n\x06source\x18\x03 \x01(\x0e\x32,.calixa.domain.integration.IntegrationSource\x12.\n\nemitted_at\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x15\n\rextraction_id\x18\x05 \x01(\t\x12\x11\n\tnamespace\x18\x06 \x01(\t\x12\x0e\n\x06stream\x18\x07 \x01(\t\x12\x0f\n\x07payload\x18\n \x01(\t\"\x97\x03\n\x0cLoadedEntity\x12,\n\x06\x65ntity\x18\x01 \x01(\x0b\x32\x1c.calixa.domain.entity.Entity\x12\x35\n\x0b\x65xternal_id\x18\x02 \x01(\x0b\x32 .calixa.domain.common.ExternalId\x12?\n\rmutation_type\x18\x03 \x01(\x0e\x32(.calixa.integration.elt.LoadMutationType\x12=\n\x0frequest_context\x18\x04 \x01(\x0b\x32$.calixa.domain.common.RequestContext\x12.\n\nemitted_at\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x35\n\x11update_field_mask\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.FieldMask\x12\x35\n\x11\x64\x65lete_field_mask\x18\x08 \x01(\x0b\x32\x1a.google.protobuf.FieldMaskJ\x04\x08\x05\x10\x06*\xa3\x01\n\x10LoadMutationType\x12\"\n\x1eLOAD_MUTATION_TYPE_UNSPECIFIED\x10\x00\x12!\n\x1dLOAD_MUTATION_TYPE_PUT_ENTITY\x10\x01\x12#\n\x1fLOAD_MUTATION_TYPE_PATCH_ENTITY\x10\x02\x12#\n\x1fLOAD_MUTATION_TYPE_EVINCE_EVENT\x10\x03\x42\x1f\n\x19io.calixa.integration.eltH\x01P\x01\x62\x06proto3')

_LOADMUTATIONTYPE = DESCRIPTOR.enum_types_by_name['LoadMutationType']
LoadMutationType = enum_type_wrapper.EnumTypeWrapper(_LOADMUTATIONTYPE)
LOAD_MUTATION_TYPE_UNSPECIFIED = 0
LOAD_MUTATION_TYPE_PUT_ENTITY = 1
LOAD_MUTATION_TYPE_PATCH_ENTITY = 2
LOAD_MUTATION_TYPE_EVINCE_EVENT = 3


_EXTRACTEDENTITY = DESCRIPTOR.message_types_by_name['ExtractedEntity']
_LOADEDENTITY = DESCRIPTOR.message_types_by_name['LoadedEntity']
ExtractedEntity = _reflection.GeneratedProtocolMessageType('ExtractedEntity', (_message.Message,), {
  'DESCRIPTOR' : _EXTRACTEDENTITY,
  '__module__' : 'integration_elt_pb2'
  # @@protoc_insertion_point(class_scope:calixa.integration.elt.ExtractedEntity)
  })
_sym_db.RegisterMessage(ExtractedEntity)

LoadedEntity = _reflection.GeneratedProtocolMessageType('LoadedEntity', (_message.Message,), {
  'DESCRIPTOR' : _LOADEDENTITY,
  '__module__' : 'integration_elt_pb2'
  # @@protoc_insertion_point(class_scope:calixa.integration.elt.LoadedEntity)
  })
_sym_db.RegisterMessage(LoadedEntity)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031io.calixa.integration.eltH\001P\001'
  _LOADMUTATIONTYPE._serialized_start=893
  _LOADMUTATIONTYPE._serialized_end=1056
  _EXTRACTEDENTITY._serialized_start=200
  _EXTRACTEDENTITY._serialized_end=480
  _LOADEDENTITY._serialized_start=483
  _LOADEDENTITY._serialized_end=890
# @@protoc_insertion_point(module_scope)
