# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pubsub.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cpubsub.proto\x12\x14\x63\x61lixa.domain.pubsub\x1a\x19google/protobuf/any.proto\x1a\x0c\x63ommon.proto\"|\n\x14PubsubMessageWrapper\x12%\n\x07message\x18\x01 \x01(\x0b\x32\x14.google.protobuf.Any\x12=\n\x0frequest_context\x18\x02 \x01(\x0b\x32$.calixa.domain.common.RequestContextB\x1d\n\x17io.calixa.domain.pubsubH\x01P\x01\x62\x06proto3')



_PUBSUBMESSAGEWRAPPER = DESCRIPTOR.message_types_by_name['PubsubMessageWrapper']
PubsubMessageWrapper = _reflection.GeneratedProtocolMessageType('PubsubMessageWrapper', (_message.Message,), {
  'DESCRIPTOR' : _PUBSUBMESSAGEWRAPPER,
  '__module__' : 'pubsub_pb2'
  # @@protoc_insertion_point(class_scope:calixa.domain.pubsub.PubsubMessageWrapper)
  })
_sym_db.RegisterMessage(PubsubMessageWrapper)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\027io.calixa.domain.pubsubH\001P\001'
  _PUBSUBMESSAGEWRAPPER._serialized_start=79
  _PUBSUBMESSAGEWRAPPER._serialized_end=203
# @@protoc_insertion_point(module_scope)
