[tool.poetry]
name = "requests-ratelimiter"
version = "0.3.2"
description = "Rate-limiting for the requests library"
authors = ["Jordan Cook"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/JWCook/requests-ratelimiter"
repository = "https://github.com/JWCook/requests-ratelimiter"
documentation = "https://requests-ratelimiter.readthedocs.io"
keywords = ["requests", "rate-limiting", "leaky-bucket"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Typing :: Typed",
]
include = [
    {format="sdist", path="*.md"},
    {format="sdist", path="test"},
]
[tool.poetry.dependencies]
python = "^3.6.2"
pyrate-limiter = ">=2.6.3"
requests = "^2.20"

# Documentation dependencies needed for Readthedocs builds
furo = {version = "2022.3.4", optional = true}
myst-parser = {version = ">=0.17", optional = true, python=">=3.7"}
sphinx = { version = "^4.3.0", optional = true }
sphinx-autodoc-typehints = { version = "^1.17", optional = true, python=">=3.7" }
sphinx-copybutton = { version = ">=0.5", optional = true }


[tool.poetry.extras]
docs = ["furo", "myst-parser", "sphinx", "sphinx-autodoc-typehints",
        "sphinx-copybutton", "sphinxcontrib-apidoc"]

[tool.poetry.dev-dependencies]
coverage = "^6.2"
pre-commit = "^2.17"
pytest = "^7.0"
pytest-cov = ">=2.11"
pytest-xdist = ">=2.2"
requests-mock = "^1.8"

# Workarounds for possible dependency issues with importlib-metadata
typing-extensions = {version = "^4.0", python = "3.7"}
zipp = {version = "^3.7", python = "3.7"}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 100
skip-string-normalization = true

[tool.coverage.run]
branch = true
source = ['requests_ratelimiter']

[tool.coverage.html]
directory = 'test-reports'

[tool.coverage.xml]
output = 'test-reports/coverage.xml'

[tool.isort]
profile = 'black'
line_length = 100
skip_gitignore = true
known_first_party = ['tests']

[tool.mypy]
ignore_missing_imports = true
