
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-11T15:56:08+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "f412827c2fefb6f5ba4a72ca5d17b3e4571ad350",
 "version": "0.4.144"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
