
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-05T01:33:51+1000",
 "dirty": false,
 "error": null,
 "full-revisionid": "2299700a06e4156cd7e3ff1ffdb9c7e01ee1f791",
 "version": "2.1.4-2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
