_target_: ekorpkit.preprocessors.normalizer.Normalizer
ftfy:
  unescape_html: true
  remove_terminal_escapes: true
  fix_encoding: true
  restore_byte_a0: true
  replace_lossy_sequences: true
  decode_inconsistent_utf8: true
  fix_c1_controls: true
  fix_latin_ligatures: true
  fix_character_width: true
  uncurl_quotes: true
  fix_line_breaks: true
  fix_surrogates: true
  remove_control_chars: true
  normalization: NFKC
  max_decode_length: 1000000
spaces:
  strip: true
  fix_whitespaces: true
  collapse_whitespaces: true
  replace_tabs: true
  num_spaces_for_tab: 4
special_characters:
  fix_hyphens: true
  fix_ellipsis: true
  fix_slashes: true
  fix_tildes: true
  fix_emoticons: false
  single_quotes_only: false
  regular_parentheses_only: false
hanja2hangle: false
num_repeats: 2
