[tool.poetry]
name = "massedit-cli"
version = "0.1.2"
description = "Python mass editor"
authors = ["Xinyuan Chen <45612704+tddschn@users.noreply.github.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/tddschn/massedit-cli"
repository = "https://github.com/tddschn/massedit-cli"
classifiers = [
	"Topic :: Utilities"
]
keywords = ["massedit", "cli"]

[tool.poetry.scripts]
massedit = "massedit_cli:main"

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/tddschn/massedit-cli/issues"

[tool.poetry.dependencies]
python = "^3.10"
massedit = "^0.69.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
toml = "^0.10.2"
yapf = "^0.32.0"
better-exceptions = "^0.3.3"
bump2version = "^1.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
