# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import virtual_sfv_pb2 as virtual__sfv__pb2


class VirtualSfvGrpcServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetData = channel.unary_unary(
                '/Bsii.SolarFocus.Protobuf.SolarField.VirtualSfvGrpcService/GetData',
                request_serializer=virtual__sfv__pb2.VirtualSfvInputsQuery.SerializeToString,
                response_deserializer=virtual__sfv__pb2.VirtualSfvInputsResult.FromString,
                )


class VirtualSfvGrpcServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VirtualSfvGrpcServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetData,
                    request_deserializer=virtual__sfv__pb2.VirtualSfvInputsQuery.FromString,
                    response_serializer=virtual__sfv__pb2.VirtualSfvInputsResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Bsii.SolarFocus.Protobuf.SolarField.VirtualSfvGrpcService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class VirtualSfvGrpcService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Bsii.SolarFocus.Protobuf.SolarField.VirtualSfvGrpcService/GetData',
            virtual__sfv__pb2.VirtualSfvInputsQuery.SerializeToString,
            virtual__sfv__pb2.VirtualSfvInputsResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
