
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-13T15:12:12+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "2ea03b76f3092764ad3ef1da3f5934469449778e",
 "version": "2671"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
