defaults:
  - /io: _build_corpus
  - /info: _build_corpus
  - /pipeline: _build_corpus

_target_: ekorpkit.io.fetch.build.DatasetBuilder
name:
data_dir: ${dir.corpus}/${.name}
# data_dir: ${dir.archive}/datasets/lmdata/${.name}
filetype: .parquet
segment_separator: \n\n
sentence_separator: \n
verbose: ${oc.select:..verbose, true}
autoload: true

normalize:
  preprocessor:
    normalizer: ${oc.select:corpus.builtin.preprocessor.normalizer,null}
segment:
  preprocessor:
    segmenter: ${oc.select:corpus.builtin.preprocessor.segmenter,null}
