[tool.poetry]
authors = ["Didier SCHMITT <dschmitt@equancy.com>"]
classifiers = [
  "Development Status :: 4 - Beta",
  "Topic :: Software Development :: Libraries :: Python Modules",
]
description = "Datalake ingestion workflow"
documentation = "https://docs.equancy.cloud/datalake-ingestion/latest/index.html"
license = "MIT"
name = "datalake-ingestion"
readme = "README.md"
repository = "https://github.com/equancy/datalake-ingestion"
version = "1.0.2"

[tool.poetry.dependencies]
PyYAML = "^6.0"
datalake-framework = "^1.0.0"
jsonschema = "^4.2.1"
pendulum = "^2.1.2"
python = "^3.8"

[tool.poetry.dev-dependencies]
Sphinx = "^4.5.0"
black = "^21.11b1"
coverage = "^6.2"
flake9 = "^3.8.3"
pytest = "^6.2.5"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]

[tool.flake8]
ignore = "E501,W503"

[tool.black]
line-length = 125
target-version = ['py38']

[tool.coverage.report]
omit = ["tests/*"]

[tool.pytest.ini_options]
addopts = "-ra -v --no-header"
minversion = "6.0"
testpaths = ["tests"]
