[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"
[project]
name = "hyper_connect"
authors = [
    {name = "Trip Ottinger", email = "trip@hyper.io"},
]
readme = "README.md"
classifiers = [
    "License :: OSI Approved :: Apache-2.0",
]
requires-python = ">=3.8"
dynamic = ["version", "description"]
dependencies = [
    "certifi"="2021.10.8",
    "cfgv"="3.3.1",
    "charset-normalizer"="2.0.12",
    "click"="8.1.3",
    "distlib"="0.3.4",
    "docutils"="0.18.1",
    "filelock"="3.6.0"

]
[project.optional-dependencies]
test = [

]
lint = [
    "autopep8"="1.6.0",
    "black"="22.3.0",

]
[project.urls]
Home = "https://github.com/tripott/hyper-connect-py-test"
