# Generated by Django 3.2.5 on 2021-07-20 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CmCodeDetail',
            fields=[
                ('cm_code_type_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('detail_code_id', models.CharField(max_length=10)),
                ('detail_code_name', models.CharField(max_length=100)),
                ('sort_seq', models.IntegerField(blank=True, null=True)),
                ('use_yn', models.CharField(max_length=1)),
                ('etc_ctnt1', models.CharField(blank=True, max_length=20, null=True)),
                ('etc_ctnt2', models.CharField(blank=True, max_length=20, null=True)),
                ('etc_ctnt3', models.CharField(blank=True, max_length=20, null=True)),
                ('etc_ctnt4', models.CharField(blank=True, max_length=20, null=True)),
                ('etc_ctnt5', models.CharField(blank=True, max_length=20, null=True)),
                ('etc_desc', models.CharField(blank=True, max_length=1000, null=True)),
                ('valid_start_date', models.DateField(blank=True, null=True)),
                ('valid_end_date', models.DateField(blank=True, null=True)),
                ('first_rg_yms', models.DateTimeField()),
                ('first_rg_idf', models.CharField(max_length=10)),
                ('last_update_yms', models.DateTimeField()),
                ('last_update_idf', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'cm_code_detail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CmCodeMaster',
            fields=[
                ('cm_code_type_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('cm_code_type_name', models.CharField(max_length=100)),
                ('parent_code_type_id', models.CharField(blank=True, max_length=10, null=True)),
                ('cm_code_length', models.IntegerField(blank=True, null=True)),
                ('system_yn', models.CharField(blank=True, max_length=1, null=True)),
                ('remark', models.CharField(blank=True, max_length=500, null=True)),
                ('first_rg_yms', models.DateTimeField()),
                ('first_rg_idf', models.CharField(max_length=10)),
                ('last_update_yms', models.DateTimeField()),
                ('last_update_idf', models.CharField(max_length=10)),
                ('delete_yn', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'cm_code_master',
                'managed': False,
            },
        ),
    ]
