[tool.poetry]
name = "from-jupyter"
version = "0.3.0"
authors = ["Antonio Feregrino <antonio.feregrino@gmail.com>"]
description = "Blogging from Jupyter notebooks"
license = "MIT"
readme = "readme.md"
homepage = "https://github.com/fferegrino/from-jupyter"
repository = "https://github.com/fferegrino/from-jupyter"

[tool.poetry.scripts]
from-jupyter = "from_jupyter.__main__:cli"

[tool.poetry.dependencies]
python = "^3.8"
imgkit = "^1.2.2"
jupytext = "^1.13.8"
requests = "^2.27.1"
Pygments = "^2.12.0"

[tool.poetry.dev-dependencies]
black = "^22.3.0"
bump2version = "^1.0.1"
isort = "^5.10.1"
jupyter = "^1.0.0"
matplotlib = "^3.5.2"
pandas = "^1.4.2"

[tool.black]
line-length = 120

[tool.isort]
skip_glob = [
    ".venv"
]
# Structure
default_section = "THIRDPARTY"
known_first_party = "from_jupyter"
# Import Style
line_length = 120
force_grid_wrap = false
use_parentheses = true
include_trailing_comma = true
combine_as_imports = true
multi_line_output = 3

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
