[tool.poetry]
name = "calculadora_do_fillipe"
version = "0.1.0"
description = "Nova biblioteca bonita em time!"
authors = ["Mariana Pinheiro <mariana.pinheiro@loggi.com>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
