
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-14T20:16:08+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "685c9ec722c060cf9f78fc9318ce59e6a43e0432",
 "version": "0.2.0.post0.dev51"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
