# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: counter.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcounter.proto\x12\x15\x63\x61lixa.domain.counter\x1a\x1fgoogle/protobuf/timestamp.proto\"{\n\nCounterKey\x12\x17\n\x0forganization_id\x18\x01 \x01(\t\x12\x0b\n\x03key\x18\x02 \x01(\t\x12\x38\n\x0c\x63ounter_type\x18\x03 \x01(\x0e\x32\".calixa.domain.counter.CounterType\x12\r\n\x05param\x18\x04 \x01(\t\"\x94\x01\n\x12\x43ounterObservation\x12.\n\x03key\x18\x01 \x01(\x0b\x32!.calixa.domain.counter.CounterKey\x12/\n\x0bobserved_at\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x03\x12\r\n\x05\x63ount\x18\x04 \x01(\x03\"c\n\x12\x43ounterValueAtTime\x12\x14\n\x0cvaluePresent\x18\x01 \x01(\x08\x12\r\n\x05value\x18\x02 \x01(\x03\x12(\n\x04time\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp*D\n\x0b\x43ounterType\x12\x1c\n\x18\x43OUNTER_TYPE_UNSPECIFIED\x10\x00\x12\x17\n\x13\x43OUNTER_TYPE_METRIC\x10\x01*\x82\x01\n\x07GroupBy\x12\x18\n\x14GROUP_BY_UNSPECIFIED\x10\x00\x12\x11\n\rGROUP_BY_HOUR\x10\x01\x12\x10\n\x0cGROUP_BY_DAY\x10\x02\x12\x11\n\rGROUP_BY_WEEK\x10\x03\x12\x12\n\x0eGROUP_BY_MONTH\x10\x04\x12\x11\n\rGROUP_BY_YEAR\x10\x05*\x92\x01\n\x12\x41ggregateOperation\x12#\n\x1f\x41GGREGATE_OPERATION_UNSPECIFIED\x10\x00\x12\x1b\n\x17\x41GGREGATE_OPERATION_SUM\x10\x01\x12\x1b\n\x17\x41GGREGATE_OPERATION_AVG\x10\x02\x12\x1d\n\x19\x41GGREGATE_OPERATION_COUNT\x10\x03\x42\x17\n\x11io.calixa.counterH\x01P\x01\x62\x06proto3')

_COUNTERTYPE = DESCRIPTOR.enum_types_by_name['CounterType']
CounterType = enum_type_wrapper.EnumTypeWrapper(_COUNTERTYPE)
_GROUPBY = DESCRIPTOR.enum_types_by_name['GroupBy']
GroupBy = enum_type_wrapper.EnumTypeWrapper(_GROUPBY)
_AGGREGATEOPERATION = DESCRIPTOR.enum_types_by_name['AggregateOperation']
AggregateOperation = enum_type_wrapper.EnumTypeWrapper(_AGGREGATEOPERATION)
COUNTER_TYPE_UNSPECIFIED = 0
COUNTER_TYPE_METRIC = 1
GROUP_BY_UNSPECIFIED = 0
GROUP_BY_HOUR = 1
GROUP_BY_DAY = 2
GROUP_BY_WEEK = 3
GROUP_BY_MONTH = 4
GROUP_BY_YEAR = 5
AGGREGATE_OPERATION_UNSPECIFIED = 0
AGGREGATE_OPERATION_SUM = 1
AGGREGATE_OPERATION_AVG = 2
AGGREGATE_OPERATION_COUNT = 3


_COUNTERKEY = DESCRIPTOR.message_types_by_name['CounterKey']
_COUNTEROBSERVATION = DESCRIPTOR.message_types_by_name['CounterObservation']
_COUNTERVALUEATTIME = DESCRIPTOR.message_types_by_name['CounterValueAtTime']
CounterKey = _reflection.GeneratedProtocolMessageType('CounterKey', (_message.Message,), {
  'DESCRIPTOR' : _COUNTERKEY,
  '__module__' : 'counter_pb2'
  # @@protoc_insertion_point(class_scope:calixa.domain.counter.CounterKey)
  })
_sym_db.RegisterMessage(CounterKey)

CounterObservation = _reflection.GeneratedProtocolMessageType('CounterObservation', (_message.Message,), {
  'DESCRIPTOR' : _COUNTEROBSERVATION,
  '__module__' : 'counter_pb2'
  # @@protoc_insertion_point(class_scope:calixa.domain.counter.CounterObservation)
  })
_sym_db.RegisterMessage(CounterObservation)

CounterValueAtTime = _reflection.GeneratedProtocolMessageType('CounterValueAtTime', (_message.Message,), {
  'DESCRIPTOR' : _COUNTERVALUEATTIME,
  '__module__' : 'counter_pb2'
  # @@protoc_insertion_point(class_scope:calixa.domain.counter.CounterValueAtTime)
  })
_sym_db.RegisterMessage(CounterValueAtTime)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\021io.calixa.counterH\001P\001'
  _COUNTERTYPE._serialized_start=450
  _COUNTERTYPE._serialized_end=518
  _GROUPBY._serialized_start=521
  _GROUPBY._serialized_end=651
  _AGGREGATEOPERATION._serialized_start=654
  _AGGREGATEOPERATION._serialized_end=800
  _COUNTERKEY._serialized_start=73
  _COUNTERKEY._serialized_end=196
  _COUNTEROBSERVATION._serialized_start=199
  _COUNTEROBSERVATION._serialized_end=347
  _COUNTERVALUEATTIME._serialized_start=349
  _COUNTERVALUEATTIME._serialized_end=448
# @@protoc_insertion_point(module_scope)
