stages:
  - prepare
  - build
  - test

update:
  stage: prepare
  script:
    - apt-get update -qq -y
    - apt-get install -qq -y build-essential gcc make
    - apt-get install -y software-properties-common xvfb libgtk2.0-0 libnotify4 freeglut3 libsdl1.2debian
    - add-apt-repository -y -r ppa:deadsnakes/ppa
    - apt update -q -y
    - apt-get update -qq -y
    - apt-get install -qq -y libbz2-dev zlib1g-dev libncurses5-dev libncursesw5-dev liblzma-dev libgtk-3-dev dpkg-dev libjpeg-dev libtiff-dev libsdl1.2-dev libnotify-dev freeglut3 freeglut3-dev libghc-gtk3-dev libwxgtk3.0-gtk3-dev libgtk-3-0
    - cat /etc/os-release

build_htslib:
  stage: build
  script:
    - cd ..
    - wget https://github.com/samtools/htslib/archive/refs/tags/1.10.2.tar.gz
    - tar xzf 1.10.2.tar.gz
    - ls
    - cd htslib-1.10.2
    - autoreconf
    - ./configure
    - make
    - make install
    - cd ..
    - echo "////////////////////"
    - ls
    
# before_script:
#   - python3 -V  # Print out python version for debugging
#   - python3 -m venv venv
#   - source venv/bin/activate
#   - pip install pip --upgrade
#   - pip install flit
#   - FLIT_ROOT_INSTALL=1 flit install

# python38:
#   image: python:3.8
#   stage: test
#   script:
#     - tox -e py38-unit
#     - tox -e py38-functional

python39:
  image: python:3.9
  stage: test
  script:
    - pip install pip --upgrade
    - pip install -f https://extras.wxpython.org/wxPython4/extras/linux/gtk3/debian-10 wxPython
    - pip install flit
    - FLIT_ROOT_INSTALL=1 flit install --deps=all
    - tox -e py39-unit-nogui
    - tox -e py39-functional-nogui

# run:
#   script:
#     - python setup.py bdist_wheel
#     # an alternative approach is to install and run:
#     - pip install dist/*
#     # run the command here
#   artifacts:
#     paths:
#       - dist/*.whl

# pages:
#   script:
#     - pip install sphinx sphinx-rtd-theme
#     - cd docs ; make html
#     - mv _build/html/ ../public/
#   artifacts:
#     paths:
#       - public
#   only:
#     - master
