[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[tool.isort]
multi_line_output=3
include_trailing_comma=true
force_grid_wrap=0
use_parentheses=true
line_length=88

[tool.pytest.ini_options]
markers = [
    "must_pass: marks tests as must passing in order for testing to continue."
]
addopts = [
    "--cov=pydepict",
    "--cov-report=html",
    "-q"
]
