# Generated by Django 3.2.5 on 2021-07-19 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeDetail',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('code_name', models.CharField(blank=True, max_length=100, null=True)),
                ('sort_seq', models.IntegerField(blank=True, null=True)),
                ('use_yn', models.CharField(blank=True, max_length=1, null=True)),
                ('remark', models.CharField(blank=True, max_length=500, null=True)),
                ('mgt_char1', models.CharField(blank=True, max_length=200, null=True)),
                ('mgt_char2', models.CharField(blank=True, max_length=200, null=True)),
                ('mgt_char3', models.CharField(blank=True, max_length=200, null=True)),
                ('mgt_char4', models.CharField(blank=True, max_length=200, null=True)),
                ('mgt_char5', models.CharField(blank=True, max_length=200, null=True)),
                ('mgt_char6', models.CharField(blank=True, max_length=200, null=True)),
                ('mgt_char7', models.CharField(blank=True, max_length=200, null=True)),
                ('mgt_char8', models.CharField(blank=True, max_length=200, null=True)),
                ('mgt_num1', models.DecimalField(blank=True, decimal_places=4, max_digits=65535, null=True)),
                ('mgt_num2', models.DecimalField(blank=True, decimal_places=4, max_digits=65535, null=True)),
                ('mgt_num3', models.DecimalField(blank=True, decimal_places=4, max_digits=65535, null=True)),
                ('mgt_num4', models.DecimalField(blank=True, decimal_places=4, max_digits=65535, null=True)),
                ('in_date', models.DateTimeField(blank=True, null=True)),
                ('in_user', models.CharField(blank=True, max_length=20, null=True)),
                ('up_date', models.DateTimeField(blank=True, null=True)),
                ('up_user', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'cm_code_detail',
                'ordering': ('code',),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CodeMaster',
            fields=[
                ('code_type', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('code_type_name', models.CharField(blank=True, max_length=100, null=True)),
                ('code_length', models.IntegerField(blank=True, null=True)),
                ('mgt_lvl', models.CharField(blank=True, max_length=1, null=True)),
                ('remark', models.CharField(blank=True, max_length=500, null=True)),
                ('mgt_char1', models.CharField(blank=True, max_length=100, null=True)),
                ('mgt_char2', models.CharField(blank=True, max_length=100, null=True)),
                ('mgt_char3', models.CharField(blank=True, max_length=100, null=True)),
                ('mgt_char4', models.CharField(blank=True, max_length=100, null=True)),
                ('mgt_char5', models.CharField(blank=True, max_length=100, null=True)),
                ('mgt_char6', models.CharField(blank=True, max_length=100, null=True)),
                ('mgt_char7', models.CharField(blank=True, max_length=100, null=True)),
                ('mgt_char8', models.CharField(blank=True, max_length=100, null=True)),
                ('mgt_num1', models.CharField(blank=True, max_length=100, null=True)),
                ('mgt_num2', models.CharField(blank=True, max_length=100, null=True)),
                ('mgt_num3', models.CharField(blank=True, max_length=100, null=True)),
                ('mgt_num4', models.CharField(blank=True, max_length=100, null=True)),
                ('popup_title', models.CharField(blank=True, max_length=100, null=True)),
                ('popup_width', models.DecimalField(blank=True, decimal_places=0, max_digits=65535, null=True)),
                ('popup_height', models.DecimalField(blank=True, decimal_places=0, max_digits=65535, null=True)),
                ('in_date', models.DateTimeField(blank=True, null=True)),
                ('in_user', models.CharField(blank=True, max_length=20, null=True)),
                ('up_date', models.DateTimeField(blank=True, null=True)),
                ('up_user', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'cm_code_master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('user_level', models.CharField(blank=True, max_length=20, null=True)),
                ('use_yn', models.CharField(blank=True, max_length=1, null=True)),
                ('emp_no', models.CharField(blank=True, max_length=20, null=True)),
                ('ext_char1', models.CharField(blank=True, max_length=50, null=True)),
                ('ext_char2', models.CharField(blank=True, max_length=50, null=True)),
                ('ext_num1', models.DecimalField(blank=True, decimal_places=0, max_digits=13, null=True)),
                ('ext_num2', models.DecimalField(blank=True, decimal_places=0, max_digits=13, null=True)),
                ('remark', models.CharField(blank=True, max_length=500, null=True)),
                ('in_date', models.DateTimeField(blank=True, null=True)),
                ('in_user', models.CharField(blank=True, max_length=20, null=True)),
                ('up_date', models.DateTimeField(blank=True, null=True)),
                ('up_user', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'cm_user',
                'managed': False,
            },
        ),
    ]
