defaults:
  - /function: save_dataframe

name: ${oc.select:..name, pipeline}
columns_to_keep:
filepath:
filetype: parquet
output_dir: ${oc.select:..output_dir, ${dir.output}/${.name}}
output_file: ${oc.select:..output_file, ${.name}.${.filetype}}
verbose: ${oc.select:..verbose, true}
