defaults:
  - _default

_target_: ekorpkit.io.fetch.fomc.build_fomc
compress: false
from_year: 1990
contents:
  - content_type: fomc_statement
    _target_: ekorpkit.io.fetch.fomc.Statement
  - content_type: fomc_minutes
    _target_: ekorpkit.io.fetch.fomc.Minutes
  # - content_type: fomc_beigebook
  #   _target_: ekorpkit.io.fetch.fomc.BeigeBook
  - content_type: fomc_speech
    _target_: ekorpkit.io.fetch.fomc.Speech
  - content_type: fomc_testimony
    _target_: ekorpkit.io.fetch.fomc.Testimony
  - content_type: fomc_meeting_script
    _target_: ekorpkit.io.fetch.fomc.MeetingScript
  - content_type: fomc_press_conf
    _target_: ekorpkit.io.fetch.fomc.PresConfScript
fomc:
  base_url: https://www.federalreserve.gov
  calendar_url: ${.base_url}/monetarypolicy/fomccalendars.htm
  segment_separator: '\n\n'
  verbose: true
  force_download: false
  num_workers: ${..num_workers}
  output_dir: ${..output_dir}
  compress: ${..compress}
  chair:
    columns: [surname, first_name, from_date, to_date]
    data:
      - [Greenspan, Alan, 1987-08-11, 2006-01-31]
      - [Bernanke, Ben, 2006-02-01, 2014-01-31]
      - [Yellen, Janet, 2014-02-03, 2018-02-03]
      - [Powell, Jerome, 2018-02-05, 2022-02-05]
recessions:
  dotcom:
    name: Dot-com Bubble
    description: Dot-com bubble
    source: https://en.wikipedia.org/wiki/Dot-com_bubble
    from: 2000-03
    to: 2002-10
    format: "%Y-%m"
  fincrisis:
    name: Financial Crisis
    description: Financial crisis of 2007-2008
    source: https://en.wikipedia.org/wiki/Financial_crisis_of_2007-2008
    from: 2007-04
    to: 2009-03
    format: "%Y-%m"
  eurodebt:
    name: Euro Debt Crisis
    description: European debt crisis
    source: https://en.wikipedia.org/wiki/European_debt_crisis
    from: 2010-09
    to: 2012-09
    format: "%Y-%m"
  chinese:
    name: Chinese Crisis
    description: 2015-16 Chinese stock market turbulence
    source: https://en.wikipedia.org/wiki/2015-2016_Chinese_stock_market_turbulence
    from: 2015-01
    to: 2016-06
    format: "%Y-%m"
  covid19:
    name: COVID-19
    description: COVID-19 Pandemic
    source: https://en.wikipedia.org/wiki/COVID-19_pandemic
    from: 2020-02
    to: 2022-02
    format: "%Y-%m"
