[tool.poetry]

name = "odap-adform-downloader"
version = "1.0.3"
description = "DataSentics adform zip downloader"
readme = "README.md"
repository = "https://github.com/DataSentics/odap-adform-downloader"

license = "MIT"

authors = [
    "Pavla"
]

classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

packages = [
    { include = "adform", from = "src" },
]

[tool.poetry.dependencies]
python = ">=3.7.1,<4.0.0"
requests = "^2.25.1"
azure-storage-blob = "^12.8.0"

[tool.poetry.dev-dependencies]
pylint = "2.4.*"
pytest = "5.2.*"
flake8 = "^3.9.1"
black = "^20.8b1"
poethepoet = "^0.10.0"

[tool.black]
line-length = 140

[tool.poe.tasks]
black = "black src"
black-check = "black --check src"
flake8 = "flake8 --ignore=E501,W503 src"

[[tool.poetry.source]]
name = "datasentics"
url = "https://pkgs.dev.azure.com/dataengineerics/_packaging/dataengineerics/pypi/simple/"
secondary = true
