[tool.poetry]
name = "polygon-api-client"
version = "v1.0.0.beta11"
description = "Official Polygon.io REST and Websocket client."
authors = ["polygon.io"]
license = "MIT"
homepage = "https://polygon.io"
repository = "https://github.com/polygon-io/client-python"
documentation = "https://polygon.io/docs"
keywords = [
  "polygon",
  "free",
  "rest",
  "stock",
  "market",
  "data",
  "api",
  "polygon.io",
  "websocket",
  "client"
]
packages = [
  { include = "polygon" }
]

[tool.poetry.dependencies]
python = "^3.7"
urllib3 = "^1.26.9"
websockets = "^10.3"
certifi = "^2021.10.8"

[tool.poetry.dev-dependencies]
black = "^22.3.0"
mypy = "^0.942"
types-urllib3 = "^1.26.13"
httpretty = "^1.1.4"
Sphinx = "^4.5.0"
sphinx-rtd-theme = "^1.0.0"
# keep this in sync with docs/requirements.txt for readthedocs.org
sphinx-autodoc-typehints = "^1.18.1"
types-certifi = "^2021.10.8"
types-setuptools = "^57.4.14"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
