[tool.poetry]
name = "pywebcanvas"
version = "0.3.0"
description = "A library that allows users to interact with the HTML Canvas with 100% Python + HTML."
authors = ["Isaac Beverly"]
readme = "README.md"
homepage = "https://gitlab.com/imbev/pywebcanvas"
repository = "https://gitlab.com/imbev/pywebcanvas.git"
keywords = ["pyscript", "web", "canvas"]
license = "LGPL-3.0-or-later"

[tool.poetry.dependencies]
python = "^3.8"
colour = "^0.1.5"
typer = "^0.4.1"

[tool.poetry.dev-dependencies]
httpserver = "^1.1.0"

[tool.poetry.scripts]
pywebcanvas = "pywebcanvas.cli:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
