[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "depwell"
authors = [{name = "labtopher", email = "no@email.thanks"}]
license = {file = "LICENSE"}
classifiers = ["License :: OSI Approved :: The Unlicense (Unlicense)"]
dynamic = ["version", "description"]
