[tool.poetry]
name = "utsc.core"
version = "2022.5.10"
description = "an opinionated set of utilities designed to be easily included in any number of projects"
readme = "README.md"
authors = ["Alex Tremblay <alex.tremblay@utoronto.ca>", "University of Toronto Governing Council <governing.council@utoronto.ca>"]
license = "MIT"
packages = [
  { include = "utsc/core", from = "src" }
]

[tool.poetry.dependencies]
python = ">=3.10,<4.0"
loguru = {version = "*"}
typer = {version = ">=0.4.0"}
rich = {version = "*"}
pydantic = {version = ">=1.9", optional = true}
jinja2 = {version = ">=3.0", optional = true}
sentry-sdk = {version = ">=1.4", optional = true}
semver = {version = "*", optional = true}
pytest = {version = ">=6.0", optional = true}
prompt-toolkit = {version = ">=3.0.0", optional = true}

[tool.poetry.extras]
all = ["pydantic", "jinja2", "sentry-sdk", "semver", "pytest", "prompt-toolkit"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
