debug: false

#    """
#    This is temporal to copy non-incremental sync tables to PG. To retire completely the sync pipeline.
#  ea.load_eligibility
#  ea.load_supplemental
#  ea.load_providers_raw
#    """

## Files to Load / Create View
variables:
- project_root_path = {config.project_root_path}
#  - cad_job_id = {config.job_id}
- client = {config.client}
- aggr_location =  {config.aggr_location}
- debug = False

Extract:

  Load_EA_Supplemental:
    type: parquet
    location: "{project_root_path}/{client}/Load_EA_Supplemental/"

  Load_EA_Providers_Raw:
    type: parquet
    location: "{project_root_path}/{client}/Load_EA_Providers_Raw/"

  Load_EA_Plan_Eligibility:
    type: parquet
    location: "{project_root_path}/{client}/Load_EA_Plan_Eligibility/"

# Note: Load tables have to be same as Extract tables.
Load:

  Load_EA_Providers_Raw:
    load_to_postgres:
      type: postgres
      conn_config_name: epia_medicare_postgres
      table_name: load_providers_raw
      mode: overwrite

  Load_EA_Supplemental:
    load_to_postgres:
      type: postgres
      conn_config_name: epia_medicare_postgres
      table_name: load_supplemental_codes
      mode: overwrite

  Load_EA_Plan_Eligibility:
    load_to_postgres:
      type: postgres
      conn_config_name: epia_medicare_postgres
      table_name: load_eligibility
      mode: overwrite
