debug: false

#    """
# one_time per client to create the inital partition (job_id = 1) for member table using EpiA current list of member_ids
# this will allow to send DELETE operations for members that not longer exist
#    """

## Files to Load / Create View
variables:
  - project_root_path = {config.project_root_path}
  - cad_job_id = {config.job_id}
  - client = {config.client}
  - aggr_location =  {config.aggr_location}
  - debug = False

Extract:
  epia_member_ids:
    type: csv
    location: "{aggr_location}/epia_member_ids.csv"

Transform:
  members_partition_1:
    sql: >-
      SELECT
        year(current_date()) as load_year,
        month(current_date()) as load_month,
        current_timestamp() as load_timestamp,
        a.member_id,
        cast(null as string) as hicn,
        cast(null as string) as mbi,
        cast(null as string) as external_member_id,
        cast(null as string) as full_name,
        cast(null as string) as first_name,
        cast(null as string) as last_name,
        cast(null as string) as gender,
        cast(null as date) as date_of_birth,
        cast(null as integer) as age,
        cast(null as string) as health_plan_member_id,
        cast(null as string) as health_plan_name,
        cast(null as string) as address_line_1,
        cast(null as string) as address_line_2,
        cast(null as string) as city,
        cast(null as string) as zip,
        cast(null as string) as state,
        cast(null as string) as phone,
        cast(null as string) as program,
        cast(null as string) as pcp_id,
        cast(null as integer) as chart_delivered_count,
        cast(null as string) as flex1,
        cast(null as string) as flex2,
        cast(null as string) as flex3,
        cast(null as string) as flex4,
        cast(null as string) as flex5,
        cast(null as string) as flex6,
        cast(null as string) as flex7,
        cast(null as string) as flex8,
        cast(null as string) as flex9,
        cast(null as string) as flex10,
        0 as hash_value,
        1  as job_id
      FROM epia_member_ids a

  member_index_partition_1:
    sql: >-
      SELECT
        a.member_id,
        cast(null as string) as hicn,
        cast(null as string) as mbi,
        cast(null as string) as external_member_id,
        cast(null as string) as full_name,
        cast(null as string) as first_name,
        cast(null as string) as last_name,
        cast(null as date) as date_of_birth,
        cast(null as integer) as age,
        cast(null as string) as gender,
        cast(null as string) as address_line_1,
        cast(null as string) as address_line_2,
        cast(null as string) as city,
        cast(null as string) as state,
        cast(null as string) as zip,
        cast(null as string) as phone,
        cast(null as string) as program,
        cast(null as string) as health_plan_member_id,
        cast(null as string) as health_plan_name,
        cast(null as integer) as chart_delivered_count,
        cast(null as string) as flex1,
        cast(null as string) as flex2,
        cast(null as string) as flex3,
        cast(null as string) as flex4,
        cast(null as string) as flex5,
        cast(null as string) as flex6,
        cast(null as string) as flex7,
        cast(null as string) as flex8,
        cast(null as string) as flex9,
        cast(null as string) as flex10,
        cast(null as string) as pcp_provider_id,
        cast(null as string) as pcp_name,
        cast(null as string) as pcp_npi,
        cast(null as string) as pcp_tax_id,
        cast(null as string) as pcp_flex1,
        cast(null as string) as pcp_flex2,
        cast(null as string) as pcp_flex3,
        cast(null as string) as pcp_flex4,
        cast(null as string) as pcp_flex5,
        cast(null as string) as pcp_flex6,
        cast(null as string) as pcp_flex7,
        cast(null as string) as pcp_flex8,
        cast(null as string) as pcp_flex9,
        cast(null as string) as pcp_flex10,
        cast(null as string) as provider_info,
        cast(null as date) as  last_encounter,
        cast(null as date) as  pcp_last_encounter,
        cast(null as date) as  spec_last_encounter,
        cast(null as integer) as  current_dos_count,
        cast(null as integer) as  current_pcp_dos_count,
        cast(null as integer) as  prior_dos_count,
        cast(null as integer) as  prior_pcp_dos_count,
        cast(null as integer) as  prior2_dos_count,
        cast(null as integer) as  prior2_pcp_dos_count,
        cast(array(null) as array<string>) as encountered_ids,
        cast(null as boolean) as current_mmr_esrd,
        cast(null as boolean) as prior_mmr_esrd,
        cast(null as boolean) as prior2_mmr_esrd,
        cast(null as boolean) as current_mmr_hospice,
        cast(null as boolean) as prior_mmr_hospice,
        cast(null as boolean) as prior2_mmr_hospice,
        cast(null as string) as current_mmr_risk_code_type,
        cast(null as string) as prior_mmr_risk_code_type,
        cast(null as string) as prior2_mmr_risk_code_type,
        cast(null as string) as current_mmr_risk_code_description,
        cast(null as string) as prior_mmr_risk_code_description,
        cast(null as string) as prior2_mmr_risk_code_description,
        cast(null as boolean) as current_is_eligible,
        cast(null as boolean) as prior_is_eligible,
        cast(null as boolean) as prior2_is_eligible,
        cast(null as date) as eligibility_date,
        cast(null as date) as eligibility_end_date,
        cast(null as string) as current_eligibility_status,
        cast(null as string) as prior_eligibility_status,
        cast(null as string) as prior2_eligibility_status,
        cast(null as integer) as current_num_months_eligible,
        cast(null as integer) as prior_num_months_eligible,
        cast(null as integer) as prior2_num_months_eligible,
        cast(null as integer) as current_recap_count,
        cast(null as integer) as prior_recap_count,
        cast(null as integer) as prior2_recap_count,
        cast(null as integer) as current_recap_opp_count,
        cast(null as integer) as prior_recap_opp_count,
        cast(null as integer) as prior2_recap_opp_count,
        cast(null as boolean) as current_wellness_visit,
        cast(null as boolean) as prior_wellness_visit,
        cast(null as boolean) as prior2_wellness_visit,
        cast(null as double) as current_raf_captured,
        cast(null as double) as prior_raf_captured,
        cast(null as double) as prior2_raf_captured,
        cast(null as double) as current_raf_demo,
        cast(null as double) as prior_raf_demo,
        cast(null as double) as prior2_raf_demo,
        cast(null as double) as current_opportunity,
        cast(null as double) as prior_opportunity,
        cast(null as double) as prior2_opportunity,
        cast(null as double) as current_raf_projected,
        cast(null as double) as prior_raf_projected,
        cast(null as double) as prior2_raf_projected,
        cast(array(null) as array<string>) as current_hcc_cap,
        cast(array(null) as array<string>) as prior_hcc_cap,
        cast(array(null) as array<string>) as prior2_hcc_cap,
        cast(array(null) as array<string>) as current_hcc_sus,
        cast(array(null) as array<string>) as prior_hcc_sus,
        cast(array(null) as array<string>) as prior2_hcc_sus,
        cast(null as double) as current_hcc_captured,
        cast(null as double) as prior_hcc_captured,
        cast(null as double) as prior2_hcc_captured,
        cast(null as double) as current_hcc_captured_source_claim,
        cast(null as double) as prior_hcc_captured_source_claim,
        cast(null as double) as prior2_hcc_captured_source_claim,
        cast(null as double) as current_hcc_captured_source_hra,
        cast(null as double) as prior_hcc_captured_source_hra,
        cast(null as double) as prior2_hcc_captured_source_hra,
        cast(null as double) as current_hcc_captured_source_hra_crr,
        cast(null as double) as prior_hcc_captured_source_hra_crr,
        cast(null as double) as prior2_hcc_captured_source_hra_crr,
        cast(null as double) as current_hcc_captured_source_mor,
        cast(null as double) as prior_hcc_captured_source_mor,
        cast(null as double) as prior2_hcc_captured_source_mor,
        cast(null as double) as current_hcc_captured_source_crr,
        cast(null as double) as prior_hcc_captured_source_crr,
        cast(null as double) as prior2_hcc_captured_source_crr,
        cast(null as double) as current_hcc_captured_source_other,
        cast(null as double) as prior_hcc_captured_source_other,
        cast(null as double) as prior2_hcc_captured_source_other,
        cast(null as double) as current_hcc_captured_new_chronic,
        cast(null as double) as prior_hcc_captured_new_chronic,
        cast(null as double) as prior2_hcc_captured_new_chronic,
        cast(null as double) as current_hcc_captured_yoy_recapture,
        cast(null as double) as prior_hcc_captured_yoy_recapture,
        cast(null as double) as prior2_hcc_captured_yoy_recapture,
        cast(null as double) as current_hcc_captured_mor_new_chronic,
        cast(null as double) as prior_hcc_captured_mor_new_chronic,
        cast(null as double) as prior2_hcc_captured_mor_new_chronic,
        cast(null as double) as current_hcc_captured_mor_yoy_recapture,
        cast(null as double) as prior_hcc_captured_mor_yoy_recapture,
        cast(null as double) as prior2_hcc_captured_mor_yoy_recapture,
        cast(null as double) as current_hcc_captured_acute,
        cast(null as double) as prior_hcc_captured_acute,
        cast(null as double) as prior2_hcc_captured_acute,
        cast(null as double) as current_hcc_captured_other,
        cast(null as double) as prior_hcc_captured_other,
        cast(null as double) as prior2_hcc_captured_other,
        cast(null as double) as current_hcc_suspects_all,
        cast(null as double) as prior_hcc_suspects_all,
        cast(null as double) as prior2_hcc_suspects_all,
        cast(null as double) as current_hcc_suspects_yoy,
        cast(null as double) as prior_hcc_suspects_yoy,
        cast(null as double) as prior2_hcc_suspects_yoy,
        cast(null as double) as current_hcc_suspects_mor_yoy,
        cast(null as double) as prior_hcc_suspects_mor_yoy,
        cast(null as double) as prior2_hcc_suspects_mor_yoy,
        cast(null as double) as current_hcc_suspects_u,
        cast(null as double) as prior_hcc_suspects_u,
        cast(null as double) as prior2_hcc_suspects_u,
        cast(null as double) as current_hcc_suspects_asr,
        cast(null as double) as prior_hcc_suspects_asr,
        cast(null as double) as prior2_hcc_suspects_asr,
        cast(null as double) as current_hcc_suspects_n,
        cast(null as double) as prior_hcc_suspects_n,
        cast(null as double) as prior2_hcc_suspects_n,
        cast(null as double) as current_hcc_suspects_cpt,
        cast(null as double) as prior_hcc_suspects_cpt,
        cast(null as double) as prior2_hcc_suspects_cpt,
        cast(null as double) as current_hcc_suspects_ml,
        cast(null as double) as prior_hcc_suspects_ml,
        cast(null as double) as prior2_hcc_suspects_ml,
        cast(null as double) as current_hcc_suspects_other,
        cast(null as double) as prior_hcc_suspects_other,
        cast(null as double) as prior2_hcc_suspects_other,
        cast(null as double) as current_hcc_suspects_clinical,
        cast(null as double) as prior_hcc_suspects_clinical,
        cast(null as double) as prior2_hcc_suspects_clinical,
        cast(null as integer) as current_hcc_captured_num_all,
        cast(null as integer) as prior_hcc_captured_num_all,
        cast(null as integer) as prior2_hcc_captured_num_all,
        cast(null as integer) as current_hcc_captured_num_source_claim,
        cast(null as integer) as prior_hcc_captured_num_source_claim,
        cast(null as integer) as prior2_hcc_captured_num_source_claim,
        cast(null as integer) as current_hcc_captured_num_source_hra,
        cast(null as integer) as prior_hcc_captured_num_source_hra,
        cast(null as integer) as prior2_hcc_captured_num_source_hra,
        cast(null as integer) as current_hcc_captured_num_source_hra_crr,
        cast(null as integer) as prior_hcc_captured_num_source_hra_crr,
        cast(null as integer) as prior2_hcc_captured_num_source_hra_crr,
        cast(null as integer) as current_hcc_captured_num_source_mor,
        cast(null as integer) as prior_hcc_captured_num_source_mor,
        cast(null as integer) as prior2_hcc_captured_num_source_mor,
        cast(null as integer) as current_hcc_captured_num_source_crr,
        cast(null as integer) as prior_hcc_captured_num_source_crr,
        cast(null as integer) as prior2_hcc_captured_num_source_crr,
        cast(null as integer) as current_hcc_captured_num_source_other,
        cast(null as integer) as prior_hcc_captured_num_source_other,
        cast(null as integer) as prior2_hcc_captured_num_source_other,
        cast(null as integer) as current_hcc_captured_num_new_chronic,
        cast(null as integer) as prior_hcc_captured_num_new_chronic,
        cast(null as integer) as prior2_hcc_captured_num_new_chronic,
        cast(null as integer) as current_hcc_captured_num_yoy_recapture,
        cast(null as integer) as prior_hcc_captured_num_yoy_recapture,
        cast(null as integer) as prior2_hcc_captured_num_yoy_recapture,
        cast(null as integer) as current_hcc_captured_num_mor_new_chronic,
        cast(null as integer) as prior_hcc_captured_num_mor_new_chronic,
        cast(null as integer) as prior2_hcc_captured_num_mor_new_chronic,
        cast(null as integer) as current_hcc_captured_num_mor_yoy_recapture,
        cast(null as integer) as prior_hcc_captured_num_mor_yoy_recapture,
        cast(null as integer) as prior2_hcc_captured_num_mor_yoy_recapture,
        cast(null as integer) as current_hcc_captured_num_acute,
        cast(null as integer) as prior_hcc_captured_num_acute,
        cast(null as integer) as prior2_hcc_captured_num_acute,
        cast(null as integer) as current_hcc_captured_num_other,
        cast(null as integer) as prior_hcc_captured_num_other,
        cast(null as integer) as prior2_hcc_captured_num_other,
        cast(null as integer) as current_hcc_suspects_num_all,
        cast(null as integer) as prior_hcc_suspects_num_all,
        cast(null as integer) as prior2_hcc_suspects_num_all,
        cast(null as integer) as current_hcc_suspects_num_yoy,
        cast(null as integer) as prior_hcc_suspects_num_yoy,
        cast(null as integer) as prior2_hcc_suspects_num_yoy,
        cast(null as integer) as current_hcc_suspects_num_mor_yoy,
        cast(null as integer) as prior_hcc_suspects_num_mor_yoy,
        cast(null as integer) as prior2_hcc_suspects_num_mor_yoy,
        cast(null as integer) as current_hcc_suspects_num_u,
        cast(null as integer) as prior_hcc_suspects_num_u,
        cast(null as integer) as prior2_hcc_suspects_num_u,
        cast(null as integer) as current_hcc_suspects_num_asr,
        cast(null as integer) as prior_hcc_suspects_num_asr,
        cast(null as integer) as prior2_hcc_suspects_num_asr,
        cast(null as integer) as current_hcc_suspects_num_n,
        cast(null as integer) as prior_hcc_suspects_num_n,
        cast(null as integer) as prior2_hcc_suspects_num_n,
        cast(null as integer) as current_hcc_suspects_num_cpt,
        cast(null as integer) as prior_hcc_suspects_num_cpt,
        cast(null as integer) as prior2_hcc_suspects_num_cpt,
        cast(null as integer) as current_hcc_suspects_num_ml,
        cast(null as integer) as prior_hcc_suspects_num_ml,
        cast(null as integer) as prior2_hcc_suspects_num_ml,
        cast(null as integer) as current_hcc_suspects_num_other,
        cast(null as integer) as prior_hcc_suspects_num_other,
        cast(null as integer) as prior2_hcc_suspects_num_other,
        cast(null as integer) as current_hcc_suspects_num_clinical,
        cast(null as integer) as prior_hcc_suspects_num_clinical,
        cast(null as integer) as prior2_hcc_suspects_num_clinical,
        cast(null as double) as current_raf_profitability,
        cast(null as double) as prior_raf_profitability,
        cast(null as double) as prior2_raf_profitability,
        cast(null as boolean) as current_dual,
        cast(null as boolean) as current_dual_opp,
        cast(null as boolean) as prior_dual,
        cast(null as boolean) as prior_dual_opp,
        cast(null as boolean) as prior2_dual,
        cast(null as boolean) as prior2_dual_opp,
        cast(null as double) as current_dual_opp_score,
        cast(null as double) as prior_dual_opp_score,
        cast(null as double) as prior2_dual_opp_score,
        cast(null as double) as current_raf_captured_cf,
        cast(null as double) as prior_raf_captured_cf,
        cast(null as double) as prior2_raf_captured_cf,
        cast(null as double) as current_raf_dual_boost,
        cast(null as double) as prior_raf_dual_boost,
        cast(null as double) as prior2_raf_dual_boost,
        cast(null as double) as current_cf_profitability,
        cast(null as double) as prior_cf_profitability,
        cast(null as double) as prior2_cf_profitability,
        cast(null as double) as current_parta_ramra_pa,
        cast(null as double) as prior_parta_ramra_pa,
        cast(null as double) as prior2_parta_ramra_pa,
        cast(null as double) as current_partb_ramra_pa,
        cast(null as double) as prior_partb_ramra_pa,
        cast(null as double) as prior2_partb_ramra_pa,
        cast(null as boolean) as current_hra_completed,
        cast(null as boolean) as prior_hra_completed,
        cast(null as boolean) as prior2_hra_completed,
        0 as hash_value,
        1  as job_id
      FROM epia_member_ids a

Load:
  members_partition_1:
    members:
      type: parquet
      location: '{aggr_location}/members_history'
      partitions:
        - job_id
      mode: overwrite

  member_index_partition_1:
    members:
      type: parquet
      location: '{aggr_location}/member_index_history'
      partitions:
        - job_id
      mode: overwrite
