# The actual configuration is in Vault.

cadmium_postgres_db:
  hostname: epitest-encrypted-cluster.cluster-cd6nk8avjbps.us-east-1.rds.amazonaws.com
  port: 5432
  database_name: Cadmium
  user: master
  password: XXXXX
  table_name: nitrogen.job

epia_medicare_postgres:
  hostname: epitest-encrypted.cd6nk8avjbps.us-east-1.rds.amazonaws.com
  port: 5432
  database_name: EpiAnalytics-Triple-S
  user: master
  password: XXXXXX
  schema: ea

fiscal_month_end: !!int 6
parent_demo_client: ac

has-rafx-dx-source: false
include-ml-suspects: false
has_ingestion_pipeline: false
anonymize_members: false
auto-mmr: false
epie_client: true
epia-lite-client: false
skip-pull-data-epie: false
has-mor: true
has-pcp: true
