{
 "title": "connectors",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "query": {
     "query": "label_values(exalead_up, instance)"
    }
   },
   {
    "name": "connector",
    "query": {
     "query": "label_values(exalead_connectors_deleted{instance=~\"$service\"}, connector)"
    }
   },
   {
    "name": "phase",
    "query": {
     "query": "label_values(exalead_connectors_deleted{instance=~\"$service\", connector=~\"$connector\"}, phase)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Scan Duration over Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "exalead_connectors_scan_duration{instance=~\"$service\", connector=~\"$connector\"}",
     "legendFormat": "{{ connector }}"
    }
   ]
  },
  {
   "title": "Scan Duration variation from previous day",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "exalead_connectors_scan_duration{instance=~\"$service\", connector=~\"$connector\"} - exalead_connectors_scan_duration{instance=~\"$service\", connector=~\"$connector\"} offset 1d",
     "legendFormat": "{{ connector }} delta"
    }
   ]
  },
  {
   "title": "Last scan status",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "exalead_connectors_scan_status{instance=~\"$service\", connector=~\"$connector\"}",
     "legendFormat": "Status"
    },
    {
     "expr": "exalead_connectors_scan_deleted_objects{instance=~\"$service\", connector=~\"$connector\"}",
     "legendFormat": "Deleted Objects"
    },
    {
     "expr": "exalead_connectors_scan_pushed_objects{instance=~\"$service\", connector=~\"$connector\"}"
    },
    {
     "expr": "exalead_connectors_scan_scanned_objects{instance=~\"$service\", connector=~\"$connector\"}"
    },
    {
     "expr": "exalead_connectors_scan_retries{instance=~\"$service\", connector=~\"$connector\"}"
    },
    {
     "expr": "exalead_connectors_scan_duration{instance=~\"$service\", connector=~\"$connector\"}"
    },
    {
     "expr": "exalead_connectors_scan_end_timestamp{instance=~\"$service\", connector=~\"$connector\"} - time()*1000"
    },
    {
     "expr": "exalead_connectors_scan_duration{instance=~\"$service\", connector=~\"$connector\"} - (exalead_connectors_scan_duration{instance=~\"$service\", connector=~\"$connector\"} offset 1d)"
    }
   ]
  },
  {
   "title": "buildGroup evolution",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "exalead_connectors_active_documents{instance=~\"$service\", connector=~\"$connector\", phase=\"buildGroup\"}",
     "legendFormat": "{{ connector }} active doc"
    },
    {
     "expr": "exalead_connectors_added{instance=~\"$service\", connector=~\"$connector\", phase=\"buildGroup\"}",
     "legendFormat": "{{ connector }} added"
    },
    {
     "expr": "exalead_connectors_deleted{instance=~\"$service\", connector=~\"$connector\", phase=\"buildGroup\"}",
     "legendFormat": "{{ connector }} deleted"
    },
    {
     "expr": "exalead_connectors_failed_deleted{instance=~\"$service\", connector=~\"$connector\", phase=\"buildGroup\"}",
     "legendFormat": "{{ connector }} failed deleted"
    },
    {
     "expr": "exalead_connectors_indexed_documents{instance=~\"$service\", connector=~\"$connector\", phase=\"buildGroup\"}",
     "legendFormat": "{{ connector }} indexed"
    },
    {
     "expr": "exalead_connectors_partial_update{instance=~\"$service\", connector=~\"$connector\", phase=\"buildGroup\"}",
     "legendFormat": "{{ connector }} partial update"
    },
    {
     "expr": "exalead_connectors_replaced{instance=~\"$service\", connector=~\"$connector\", phase=\"buildGroup\"}",
     "legendFormat": "{{ connector }} replaced"
    },
    {
     "expr": "exalead_connectors_total{instance=~\"$service\", connector=~\"$connector\", phase=\"buildGroup\"}",
     "legendFormat": "{{ connector }} total"
    }
   ]
  },
  {
   "title": "Daily variation of the buildGroup element count",
   "type": "graph",
   "description": "the variation of the number of elements with 1 day interval.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max_over_time(exalead_connectors_indexed_documents{instance=~\"$service\", connector=~\"$connector\", phase=\"buildGroup\"}[24h]) \n-\nmax_over_time( exalead_connectors_indexed_documents{instance=~\"$service\", connector=~\"$connector\", phase=\"buildGroup\"}[24h] offset 1d)",
     "legendFormat": "{{ connector }} indexed"
    }
   ]
  },
  {
   "title": "buildGroup index rate 5 min",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(exalead_connectors_indexed_documents{instance=~\"$service\", connector=~\"$connector\", phase=\"buildGroup\"}[5m] )",
     "legendFormat": "{{ connector }} indexed"
    }
   ]
  },
  {
   "title": "consolidationServer evolution",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "exalead_connectors_active_documents{instance=~\"$service\", connector=~\"$connector\", phase=\"consolidationServer\"}",
     "legendFormat": "{{ connector }} active doc"
    },
    {
     "expr": "exalead_connectors_added{instance=~\"$service\", connector=~\"$connector\", phase=\"consolidationServer\"}",
     "legendFormat": "{{ connector }} added"
    },
    {
     "expr": "exalead_connectors_deleted{instance=~\"$service\", connector=~\"$connector\", phase=\"consolidationServer\"}",
     "legendFormat": "{{ connector }} deleted"
    },
    {
     "expr": "exalead_connectors_failed_deleted{instance=~\"$service\", connector=~\"$connector\", phase=\"consolidationServer\"}",
     "legendFormat": "{{ connector }} failed deleted"
    },
    {
     "expr": "exalead_connectors_indexed_documents{instance=~\"$service\", connector=~\"$connector\", phase=\"consolidationServer\"}",
     "legendFormat": "{{ connector }} indexed"
    },
    {
     "expr": "exalead_connectors_partial_update{instance=~\"$service\", connector=~\"$connector\", phase=\"consolidationServer\"}",
     "legendFormat": "{{ connector }} partial update"
    },
    {
     "expr": "exalead_connectors_replaced{instance=~\"$service\", connector=~\"$connector\", phase=\"consolidationServer\"}",
     "legendFormat": "{{ connector }} replaced"
    },
    {
     "expr": "exalead_connectors_total{instance=~\"$service\", connector=~\"$connector\", phase=\"consolidationServer\"}",
     "legendFormat": "{{ connector }} total"
    }
   ]
  },
  {
   "title": "Daily variation of the number of elements",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max_over_time(exalead_connectors_total{instance=~\"$service\", connector=~\"$connector\", phase=\"consolidationServer\"}[24h])\n-\nmax_over_time(exalead_connectors_total{instance=~\"$service\", connector=~\"$connector\", phase=\"consolidationServer\"}[24h] offset 24h)\n",
     "legendFormat": "{{ connector }} total"
    }
   ]
  },
  {
   "title": "consolidationServer total rate 5 min",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(exalead_connectors_total{instance=~\"$service\", connector=~\"$connector\", phase=\"consolidationServer\"}[5m] )",
     "legendFormat": "{{ connector }} indexed"
    }
   ]
  }
 ]
}