{
 "title": "Exalead Licence",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Licence Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Expiration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "exalead_license_status" }
   ]
  },
  {
   "title": "Expiration Grace",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "exalead_license_expiration_grace"
    }
   ]
  },
  {
   "title": "Expiration In",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "exalead_license_expire_timestamp - (time() * 1000)",
     "legendFormat": "{{ company }} / {{ type }}"
    }
   ]
  },
  {
   "title": "Expiration Date",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "exalead_license_expire_timestamp"
    }
   ]
  },
  {
   "title": "Licenced to",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "exalead_license_expire_timestamp"
    }
   ]
  },
  {
   "title": "Licenced type",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "exalead_license_expire_timestamp"
    }
   ]
  },
  {
   "title": "Licence Token Usage %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "exalead_license_tokenstatus_used / exalead_license_tokenstatus_available",
     "legendFormat": "tokens used %"
    }
   ]
  },
  { "title": "Config", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "AdvancedDocumentConversion",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "exalead_license_config_hasadvanceddocumentconversion"
    }
   ]
  },
  {
   "title": "AdvancedQueryReporting",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "exalead_license_config_hasadvancedqueryreporting"
    }
   ]
  },
  {
   "title": "ContentRecommender",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "exalead_license_config_hascontentrecommender"
    }
   ]
  },
  {
   "title": "Crawler",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "exalead_license_config_hascrawler"
    }
   ]
  },
  {
   "title": "ExtendedLanguages",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "exalead_license_config_hasextendedlanguages"
    }
   ]
  },
  {
   "title": "MashupBuilderPremium",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "exalead_license_config_hasmashupbuilderpremium"
    }
   ]
  },
  {
   "title": "OCR",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "exalead_license_config_hasocr" }
   ]
  },
  {
   "title": "SemanticFactory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "exalead_license_config_hassemanticfactory"
    }
   ]
  }
 ]
}