
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-10T10:59:13-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "667077afdb14caaeda1d067113a8b5fee8fc4a78",
 "version": "0.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
