[tool.poetry]
name = "hko"
version = "0.2.0"
description = "An unofficial Python wrapper for public API of Hong Kong Observatory"
authors = ["MisterCommand <anthonyhou04@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/MisterCommand/python-hko"
repository = "https://github.com/MisterCommand/python-hko"
keywords = ["hko", "weather"]

[tool.poetry.dependencies]
python = "^3.7"
aiohttp = "^3.7.4"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
