
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-13T13:08:06+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "9489592ef573181e8e64775274a1c661a4d7bccb",
 "version": "0.1.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
