wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.6
    framework: huggingface
    huggingface_version: 4.12.5
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
    start_time: 1642230606
    t:
      1:
      - 1
      - 3
      - 9
      - 11
      2:
      - 1
      - 3
      - 9
      - 11
      3:
      - 13
      - 16
      4: 3.8.5
      5: 0.12.6
      6: 4.12.5
      8:
      - 5
actor_batch_size:
  desc: null
  value: 256
autoresume:
  desc: null
  value: false
baseline_cost:
  desc: null
  value: 0.5
batch_size:
  desc: null
  value: 64
checkpoint_interval:
  desc: null
  value: 600
ckpt_path:
  desc: null
  value: ${savedir}/latest.ckpt
connect:
  desc: null
  value: 100.97.69.72:4431
debug:
  desc: null
  value: false
device:
  desc: null
  value: cuda:0
discounting:
  desc: null
  value: 0.99
entropy_cost:
  desc: null
  value: 0.05
env:
  desc: null
  value:
    name: msgr_train-all_s1-v0
    time_penalty: -0.02
grad_clip_norm:
  desc: null
  value: 40
local_name:
  desc: null
  value: ${name}-${peer}
localdir:
  desc: null
  value: ${savedir}/peers/${peer}
log_fmt:
  desc: null
  value: '[%(levelname)s:${name} %(module)s:%(lineno)d %(asctime)s] %(message)s'
log_interval:
  desc: null
  value: 10
max_steps:
  desc: null
  value: 100000000
model:
  desc: null
  value:
    demb: 100
    drep: 400
    drnn: 200
    field_attn: false
    name: multi
    num_film: 5
    stateful: false
    use_grid_attn: false
    use_local_conv: false
name:
  desc: null
  value: ${env.name}-${model.name}-${suffix}
num_actor_batches:
  desc: null
  value: 2
num_actor_cpus:
  desc: null
  value: 4
optimizer:
  desc: null
  value:
    alpha: 0.99
    epsilon: 0.01
    learning_rate: 0.0005
    momentum: 0
peer:
  desc: null
  value: 0
project:
  desc: null
  value: silg-moolib
reward_clip:
  desc: null
  value: 1.0
savedir:
  desc: null
  value: ${oc.env:PWD}/saves/${name}
suffix:
  desc: null
  value: 8
unroll_length:
  desc: null
  value: 20
virtual_batch_size:
  desc: null
  value: 256
wandb:
  desc: null
  value:
    enable: true
    entity: ${oc.env:USER}
    name: ${name}
    project: ${project}
warmup:
  desc: null
  value: 0
