_target_: ekorpkit.visualize.classification.plot_confusion_matrix
# data: confusion matrix to be passed in
data:
confusion_matrix:
  display_labels: auto
  # List of strings containing the display_labels to be displayed on the x,y axis. Default is 'auto'
  matrix_labels:
  # List of strings that represent the labels row by row to be shown in each square.
  include_values: true
  # If True, show the raw number in the confusion matrix. Default is True.
  include_percentages: true
  # If True, show the proportions for each category. Default is True.
  summary_stats: true
  # If True, display summary statistics below the figure. Default is True.
  cbar: true
  # If True, show the color bar. The cbar values are based off the values in the confusion matrix.
  # Default is True.
  cmap: Blues
  # Colormap of the values displayed from matplotlib.pyplot.cm. Default is 'Blues'
plot:
  figsize: (10, 5)
  style: fivethirtyeight
  rcParams:
    axes.unicode_minus: False
    axes.labelsize: 14
    axes.grid: false
    text.color: dimgrey
    font.family: sans-serif
  fontpath:
  language:
figure:
  xlabel:
    xlabel: Predicted label
  ylabel:
    ylabel: Actual label
  title:
    label:
output_dir: ${oc.select:..output_dir, .}
output_file: ${oc.select:..output_file, cm.png}
savefig:
  fname: ${..output_dir}/${..output_file}
  dpi: 300
verbose: ${oc.select:verbose, true}
