version: '{build}'

environment:
    matrix:
        - PYTHON_EXE: "C:\\Python36-x64\\python.exe"
        - PYTHON_EXE: "C:\\Python37-x64\\python.exe"
        - PYTHON_EXE: "C:\\Python38-x64\\python.exe"
        - PYTHON_EXE: "C:\\Python39-x64\\python.exe"

install:
    - configure --dev

build: off

test_script:
    - 'tmp\Scripts\activate'
    - 'tmp\Scripts\python -c "from __future__ import print_function;import sys;print(sys.getdefaultencoding())"'
    - 'tmp\Scripts\pytest -vvs'

