
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-29T09:31:33-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "7d07260bb28add3548790e706acbc61209d19a6b",
 "version": "2.1.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
