# MPB User Configuration file.

player = "/usr/sbin/smplayer"                                                  # the player to use.

use_pager = false                                                              # use pager (see README.md for more info)

[database]
    db_uri = "http://user:password@localhost:5984"                             # Database URI.


[defaults]
    user = "drad"                                                              # default user (so you dont need to supply the --user param
    source = "gaz"                                                             # default source (so you dont need to supply the --source param


[injest]
    # file types to injest
    file_types = ['*.3g2', '*.3gp', '*.AVI', '*.MOV', '*.MP4', '*.asf', '*.avi', '*.m4v', '*.mkv', '*.mp4', '*.mpg', '*.ogv', '*.webm']


[source_mappings]                                                              # source mappings map a source to a base path.
  gaz-opt = "/opt/media"
  gaz-festus = "/mnt/media/video"
