[tool.poetry]
name = "jaxmd_tools"
version = "0.1.3"
description = ""
authors = ["Minjoon Hong <mjhong0708@yonsei.ac.kr>"]

[tool.poetry.dependencies]
python = "^3.9"
jax-md = "^0.1.28"
ase = "^3.22.1"
termcolor = "^1.1.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
ipykernel = "^6.13.0"
mypy = "^0.950"
flake8 = "^4.0.1"
black = "^22.3.0"
isort = "^5.10.1"

[tool.black]
line-length = 100
target-version = ['py38', 'py39', 'py310']

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
