[tool.poetry]
name = "deep_dance"
version = "0.2.0"
description = ""
authors = ["AeRabelais <pantagruelspendulum@protonmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
cleo = "^0.8.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[tool.poetry.scripts]
deep_dance = "deep_dance.client.dance_application:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
