[tool.poetry.scripts]
jsp = "py_json_to_proto.cli:main"

[tool.poetry]
name = "py_json_to_proto"
version = "0.1.3"
authors = ["benjamin garrard <benjamingarrard5279@gmail.com>"]
license = "MIT"
readme="README.md"
description = "file:README.md"
repository="https://github.com/B2Gdevs/PyJsonToProto"

[tool.poetry.dependencies]
python = "^3.6.3"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

packages = [
    { include = "py_json_to_proto" }
]