
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-15T13:51:19+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "fead4e7f7e5516a56c51076a8bdaa1b2f1337ae0",
 "version": "1.2.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
