[project]
name = "pyddb"
version = "0.1.16"
description = "merge adb and tidevice"
authors = [
    {name = "ruomubingfeng", email = "ruomubingfeng@163.com"},
]
license-expression = "MIT"
dependencies = [
    "tidevice>=0.6.6"]
requires-python = ">=3.8"

[project.urls]
Homepage = "https://github.com/ruomubingfeng/pyddb"
[tool.pdm]

[build-system]
requires = ["pdm-pep517>=0.12.0"]
build-backend = "pdm.pep517.api"
