name: Linters

on:
  # push:
  #   branches: 
  #     - "**"
  pull_request:
    types: [opened, reopened]
    branches:
      - main

jobs:

  isort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: isort/isort-action@master

  black:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: black
        uses: psf/black@stable
