[tool.poetry]
name = "comis"
version = "0.1.0"
description = "comis, the simplest way to create a reddit bot"
authors = ["Endercheif"]
packages = [{ "include" = "comis" }]

[tool.poetry.dependencies]
python = "^3.10"
PyYAML = "^6.0"
asyncpraw = "^7.5.0"
Sphinx = {version = "^4.5.0", optional = true}
sphinx-autodoc-typehints = {version = "^1.18.1", optional = true}
pydata-sphinx-theme = {version = "^0.8.1", optional = true}


[tool.poetry.dev-dependencies]
pytest = "^5.2"
mypy = "^0.941"
black = "^22.3.0"
isort = "^5.10.1"
python-dotenv = "^0.20.0"
flake8 = "^4.0.1"

[tool.poetry.extras]
docs = ["Sphinx", "pydata-sphinx-theme", "sphinx-autodoc-typehints"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"