
# This file was generated by 'versioneer.py' (0.15+dev) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "61a0aef722e175df9cbee9a36e45396e43c16046",
 "version": "1.1.post15"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
