"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import layer.api.ids_pb2
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class ModelMetric(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    class Point(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor
        VALUE_FIELD_NUMBER: builtins.int
        TIMESTAMP_FIELD_NUMBER: builtins.int
        value: builtins.float
        timestamp: builtins.int
        def __init__(self,
            *,
            value: builtins.float = ...,
            timestamp: builtins.int = ...,
            ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["timestamp",b"timestamp","value",b"value"]) -> None: ...

    ID_FIELD_NUMBER: builtins.int
    MODEL_TRAIN_ID_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    POINTS_FIELD_NUMBER: builtins.int
    ORGANIZATION_ID_FIELD_NUMBER: builtins.int
    @property
    def id(self) -> api.ids_pb2.ModelMetricId: ...
    @property
    def model_train_id(self) -> api.ids_pb2.ModelTrainId: ...
    name: typing.Text
    @property
    def points(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ModelMetric.Point]: ...
    @property
    def organization_id(self) -> api.ids_pb2.OrganizationId: ...
    def __init__(self,
        *,
        id: typing.Optional[api.ids_pb2.ModelMetricId] = ...,
        model_train_id: typing.Optional[api.ids_pb2.ModelTrainId] = ...,
        name: typing.Text = ...,
        points: typing.Optional[typing.Iterable[global___ModelMetric.Point]] = ...,
        organization_id: typing.Optional[api.ids_pb2.OrganizationId] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["id",b"id","model_train_id",b"model_train_id","organization_id",b"organization_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["id",b"id","model_train_id",b"model_train_id","name",b"name","organization_id",b"organization_id","points",b"points"]) -> None: ...
global___ModelMetric = ModelMetric
