[tool.poetry]
name = "p3do"
version = "0.1.7"
description = "CLI utilities for p3d"
authors = ["Armin Friedl <armin.friedl@semantic-web.com>"]
readme = "README.md"
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
python-keycloak = "^0.27"
click = "^8.1"
urllib3 = "^1.26.9" # we don't actually need that directly but older versions
                    # are incompatible with python-keycloak
requests = "^2.27.1" # same here just make sure python-keycloak works

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[tool.poetry.scripts]
p3do = 'p3do.cli:cli'

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
