__version__ = '1.0.7'
__summary__ = 'Python interface to the Janelia Dudman lab mouse lickport array.'
__license__ = 'BSD 3-Clause License'
__url__ = 'https://github.com/janelia-pypi/lickport_array_interface_python'
__author__ = 'Peter Polidoro'
__email__ = 'peter@polidoro.io'
__copyright__ = '2022 Howard Hughes Medical Institute'
