# Generated by Django 4.0.4 on 2022-05-10 02:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('name', 'organization_id')},
        ),
        migrations.AddField(
            model_name='department',
            name='path',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(verbose_name='上级部门ID'), null=True, size=None, verbose_name='所属部门路径'),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='部门是否删除, 默认False'),
        ),
        migrations.AlterIndexTogether(
            name='department',
            index_together={('organization_id', 'is_deleted')},
        ),
        migrations.RemoveField(
            model_name='department',
            name='parent',
        ),
    ]
