name: release
on:
  push:
    branches:
      - main

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    environment: main
    concurrency: release
    steps:
      - name: Wait for tests to succeed
        uses: lewagon/wait-on-check-action@v1.0.0
        with:
          ref: ${{ github.ref }}
          running-workflow-name: release
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Python Semantic Release
        uses: relekang/python-semantic-release@v7.28.1
        with:
          github_token: ${{ secrets.GH_RELEASE_TOKEN }}
          repository_username: __token__
          repository_password: ${{ secrets.PYPI_API_TOKEN }}
