[tool.poetry]
name = "namer"
version = "1.2.4"
description = "A namer of video files based on metadata from the porndb."
readme = "readme.rst"
authors = ["4c0d3r <4c0d3r@protonmail.com>"]

[tool.flake8]
max-line-length = 130
count = true


[tool.poetry.dependencies]
python = "^3.8"
rapidfuzz = "^2.0.5"
watchdog = "^2.1.6"
pathvalidate = "^2.5.0"
requests = "^2.27.1"
mutagen = "^1.45.1"
lxml = "^4.8.0"
schedule = "^1.1.0"
loguru = "^0.6.0"
Unidecode = "^1.3.4"
flake8 = "^4.0.1"
Flake8-pyproject = "^0.9.0"
autopep8 = "^1.6.0"
pylint = "^2.13.8"

[tool.poetry.dev-dependencies]
pytest = "^7.0.0"
pylint = "^2.12.2"
pytest-cov = "^3.0.0"
freezegun = "^1.1.0"
coverage = "^6.3.2"
