[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "datafi"
authors = [{name = "Sekhar Ravinutala", email = "sekhar@datafi.us"}]
dynamic = ["version", "description"]

[project.urls]
Home = "https://datafi.us"
